// BuzzArena — Banque de questions (français)
// Chaque question : [texte, [choix A, choix B, choix C, choix D], indexRéponseCorrecte]
// Thèmes disponibles : general, contemporary, history, cinema, sport, animals, capitals, flags,
// literature, dance, theatre, judo
// Les questions "capitals" et "flags" sont composées à partir d'une liste de ~190 pays
// et de descriptions de drapeaux distinctives, générées puis vérifiées manuellement.
const QUESTION_BANK = {
  general: [
    ["Quelle planète est surnommée la planète rouge ?",["Vénus","Mars","Jupiter","Mercure"],1],
    ["Quel est le plus grand océan du monde ?",["Atlantique","Indien","Arctique","Pacifique"],3],
    ["Combien de côtés possède un hexagone ?",["5","6","7","8"],1],
    ["Quel gaz les plantes absorbent-elles principalement ?",["Oxygène","Hydrogène","Dioxyde de carbone","Azote"],2],
    ["Dans quel pays se trouve la ville de Kyoto ?",["Chine","Corée du Sud","Japon","Thaïlande"],2],
    ["Quel instrument mesure les séismes ?",["Baromètre","Sismographe","Altimètre","Hygromètre"],1],
    ["Quel est le symbole chimique de l’or ?",["Ag","Au","O","Or"],1],
    ["Combien de joueurs une équipe de football aligne-t-elle au coup d’envoi ?",["9","10","11","12"],2],
    ["Quel est le plus long fleuve d’Afrique ?",["Congo","Niger","Nil","Zambèze"],2],
    ["Quelle langue est principalement parlée au Brésil ?",["Espagnol","Portugais","Français","Italien"],1],
    ["Quel organe pompe le sang dans le corps humain ?",["Poumon","Foie","Cœur","Rein"],2],
    ["Quelle est la capitale du Canada ?",["Toronto","Montréal","Ottawa","Vancouver"],2],
    ["Quel métal est liquide à température ambiante ?",["Fer","Mercure","Cuivre","Aluminium"],1],
    ["Combien de minutes y a-t-il dans deux heures ?",["100","110","120","140"],2],
    ["Quel animal est le plus grand mammifère vivant ?",["Éléphant d’Afrique","Baleine bleue","Girafe","Requin-baleine"],1],
    ["Quel continent compte le plus de pays ?",["Europe","Asie","Afrique","Amérique du Sud"],2],
    ["Quel est le résultat de 12 × 8 ?",["86","92","96","108"],2],
    ["Quelle couleur obtient-on en mélangeant bleu et jaune ?",["Orange","Vert","Violet","Marron"],1],
    ["Quel est le plus petit pays du monde ?",["Vatican","Monaco","Saint-Marin","Liechtenstein"],0],
    ["Quel est le plus haut sommet du monde ?",["K2","Kilimandjaro","Everest","Mont Blanc"],2],
    ["Quelle est la plus grande planète du système solaire ?",["Saturne","Jupiter","Neptune","Uranus"],1],
    ["Combien d'os compte le corps humain adulte, en moyenne ?",["186","206","226","246"],1],
    ["Quel est le symbole chimique du sodium ?",["So","Sd","Na","Sn"],2],
    ["Quelle est la monnaie officielle du Japon ?",["Won","Yuan","Yen","Ringgit"],2],
    ["Quel est le plus grand désert chaud du monde ?",["Kalahari","Gobi","Sahara","Namib"],2],
    ["Combien de jours la Terre met-elle environ à faire le tour du Soleil ?",["30","180","365","500"],2],
    ["Quel est le plus petit os du corps humain ?",["Le fémur","L'étrier","La rotule","Le tibia"],1],
    ["Quel élément chimique est le plus abondant dans l'univers ?",["Oxygène","Carbone","Hydrogène","Hélium"],2],
    ["Combien de dents compte un adulte humain avec ses dents de sagesse ?",["28","30","32","34"],2],
    ["Quel est le plus long os du corps humain ?",["Le tibia","Le fémur","L'humérus","Le péroné"],1],
    ["Combien de côtés possède un octogone ?",["6","7","8","9"],2],
    ["Quel est le plus grand pays du monde par sa superficie ?",["Chine","Canada","États-Unis","Russie"],3],
    ["Quelle planète est la plus proche du Soleil ?",["Vénus","Mercure","Mars","la Terre"],1],
    ["Combien de couleurs compte traditionnellement l'arc-en-ciel ?",["5","6","7","8"],2],
    ["Quel est l'organe le plus étendu du corps humain ?",["Le foie","Le cœur","La peau","Le cerveau"],2],
    ["Quelle est la formule chimique de l'eau ?",["CO2","H2O","O2","NaCl"],1],
    ["Combien de jours compte une année bissextile ?",["364","365","366","367"],2],
    ["Quel gaz représente environ 78 % de l'atmosphère terrestre ?",["Oxygène","Azote","Dioxyde de carbone","Hydrogène"],1],
    ["Quelle est la plus grande île du monde ?",["Madagascar","Bornéo","Groenland","Sumatra"],2],
    ["Combien de zéros contient le nombre un million ?",["4","5","6","7"],2],
    ["Quel est le plus petit nombre premier ?",["0","1","2","3"],2],
    ["Quel fleuve est traditionnellement considéré comme le plus long du monde ?",["L'Amazone","le Nil","le Mississippi","le Yangtsé"],1],
    ["Combien de faces possède un cube ?",["4","5","6","8"],2],
    ["Quel sport est considéré comme le sport national du Japon ?",["Le judo","Le sumo","Le karaté","Le baseball"],1],
    ["Quelle partie de la fleur produit le pollen ?",["Le pistil","L'étamine","Le pétale","La tige"],1],
    ["Quelle est la principale source d'énergie de la Terre ?",["Le vent","Le Soleil","La Lune","Les volcans"],1],
    ["Combien de pattes possède un insecte ?",["4","6","8","10"],1],
    ["Quelle planète possède les anneaux les plus visibles du système solaire ?",["Jupiter","Uranus","Saturne","Neptune"],2],
    ["À quelle température l'eau bout-elle au niveau de la mer, en degrés Celsius ?",["90","100","110","120"],1],
    ["Quel est le plus grand pays d'Amérique du Sud ?",["Argentine","Pérou","Brésil","Colombie"],2],
    ["Quelle est la langue officielle de l'Égypte ?",["Le français","L'arabe","Le turc","L'hébreu"],1],
    ["Combien de lettres compte l'alphabet français ?",["24","25","26","27"],2],
    ["Quel instrument sert à mesurer la pression atmosphérique ?",["Le thermomètre","Le baromètre","L'altimètre","L'hygromètre"],1],
    ["Quel est le plus profond point connu des océans, situé dans le Pacifique ?",["La fosse des Mariannes","La fosse du Japon","La fosse de Porto Rico","La fosse des Kouriles"],0],
    ["Quelle est l'unité de mesure de la force en physique ?",["Le watt","Le newton","Le joule","Le pascal"],1],
    ["Combien de continents distingue-t-on selon le modèle enseigné en France (Europe, Asie, Afrique, Amérique, Océanie, Antarctique) ?",["4","5","6","7"],2],
    ["Quel métal précieux est traditionnellement associé aux noces d'or (50 ans de mariage) ?",["L'argent","Le platine","L'or","Le bronze"],2],
    ["Quelle mer est la plus salée du monde ?",["La mer Rouge","La mer Morte","La mer Noire","La mer Baltique"],1],
    ["Quel est le plus grand pays d'Afrique par sa superficie ?",["Nigéria","Algérie","Égypte","Afrique du Sud"],1],
    ["Combien de minutes compte une heure et demie ?",["60","75","90","100"],2]
  ],
  contemporary: [
    ["Quel réseau social est connu pour ses vidéos courtes verticales ?",["LinkedIn","TikTok","Reddit","Wikipedia"],1],
    ["Que signifie l’abréviation IA ?",["Internet automatisé","Intelligence artificielle","Interface avancée","Information augmentée"],1],
    ["Quel service est principalement utilisé pour regarder des séries en streaming ?",["Netflix","Dropbox","Slack","Waze"],0],
    ["Quel appareil portable compte souvent les pas ?",["Routeur","Montre connectée","Scanner","Projecteur"],1],
    ["Quel format est couramment utilisé pour les podcasts ?",["Audio","Tableur","Image fixe","Carte papier"],0],
    ["Quel terme désigne une émission diffusée en direct sur internet ?",["Livestream","Firmware","Cookie","Hashtag"],0],
    ["Quelle technologie permet le paiement sans contact ?",["NFC","VGA","FTP","GPS"],0],
    ["Quel symbole précède souvent un mot-clé sur les réseaux sociaux ?",["&","#","%","@"],1],
    ["Quel service permet des réunions vidéo en ligne ?",["Zoom","Excel","Photoshop","Spotify"],0],
    ["Quel terme désigne une fausse information largement diffusée ?",["Podcast","Désinformation","Archive","Playlist"],1],
    ["Quel objet est utilisé pour recharger un smartphone sans câble ?",["Chargeur à induction","Carte SIM","Disque dur","Clé USB"],0],
    ["Quel terme désigne une personne qui crée régulièrement du contenu en ligne ?",["Influenceur","Archiviste","Imprimeur","Cartographe"],0],
    ["Quel système d’exploitation équipe de nombreux iPhone ?",["Android","Linux","iOS","Windows"],2],
    ["Quel service stocke des fichiers à distance sur internet ?",["Cloud","Bluetooth","BIOS","Cache"],0],
    ["Quel terme désigne une monnaie numérique décentralisée ?",["Cryptomonnaie","Coupon","Action papier","Jeton de métro"],0],
    ["Quel type de casque ajoute des éléments numériques au monde réel ?",["Réalité augmentée","Radio FM","Infrarouge","Télétexte"],0],
    ["Quel mot désigne une image humoristique virale sur internet ?",["Mème","Codec","Script","Pixel mort"],0],
    ["Quel format de contenu disparaît souvent après 24 heures ?",["Story","Wiki","Forum","Newsletter"],0],
    ["Que signifie l'abréviation GPS ?",["Global Positioning System","General Public Service","Global Phone Signal","General Position Sensor"],0],
    ["Que signifie l'abréviation PDF ?",["Personal Data File","Portable Document Format","Public Data Format","Printable Document File"],1],
    ["Quel terme désigne un logiciel conçu pour nuire à un ordinateur ?",["Un cookie","Un malware","Un plugin","Un widget"],1],
    ["Quel terme désigne l'ensemble des objets du quotidien connectés à internet ?",["Le cloud","L'internet des objets","Le big data","Le streaming"],1],
    ["Quel terme désigne une vidéo ou une image qui se propage très rapidement sur internet ?",["Un tutoriel","Un contenu viral","Un podcast","Un webinaire"],1],
    ["Quelle technologie permet d'imprimer des objets en volume, couche par couche ?",["L'impression 3D","La réalité augmentée","Le clonage numérique","La modélisation 2D"],0],
    ["Quel terme désigne un programme informatique simulant une conversation ?",["Un chatbot","Un navigateur","Un pare-feu","Un pilote"],0],
    ["Quel terme désigne le fait de travailler à distance depuis son domicile ?",["Le co-working","Le télétravail","Le freelance","L'intérim"],1],
    ["Quel terme désigne un ensemble de données si volumineux qu'il dépasse les outils classiques d'analyse ?",["Le big data","Le cloud","Le firmware","Le backup"],0],
    ["Quelle abréviation désigne un format audio compressé très répandu ?",["WAV","MP3","PDF","RAW"],1],
    ["Quel terme désigne une tentative de tromper un internaute par un faux e-mail pour voler ses données ?",["Le phishing","Le streaming","Le blogging","Le mining"],0],
    ["Quel terme désigne une mise à jour corrective d'un logiciel ?",["Un patch","Un plugin","Un cache","Un cookie"],0],
    ["Quel objet connecté mesure souvent le rythme cardiaque et le sommeil ?",["Une montre connectée","Un routeur","Une clé USB","Un disque dur"],0],
    ["Quel terme désigne un jeu vidéo auquel plusieurs personnes jouent ensemble en ligne ?",["Solo","Multijoueur","Hors-ligne","Rétrocompatible"],1],
    ["Quelle abréviation désigne la réalité augmentée ?",["VR","RA","IA","3D"],1],
    ["Quelle abréviation désigne la réalité virtuelle ?",["RV","RA","IA","4K"],0],
    ["Quel terme désigne une personne qui monétise son influence sur les réseaux sociaux ?",["Un modérateur","Un influenceur","Un développeur","Un hébergeur"],1],
    ["Quel terme désigne le fait de faire défiler du contenu sur un écran tactile ?",["Scroller","Cliquer","Streamer","Charger"],0],
    ["Quel terme désigne un espace de discussion textuelle instantanée en ligne ?",["Un forum","Un chat","Un blog","Un wiki"],1],
    ["Quel type de contenu combine texte, images, sons et vidéos de façon interactive ?",["Un multimédia","Un exécutable","Un firmware","Un protocole"],0],
    ["Quel terme désigne un enregistrement audio que l'on peut télécharger ou écouter en streaming ?",["Un podcast","Un widget","Un cookie","Un tag"],0],
    ["Quel terme désigne le stockage de fichiers sur des serveurs distants accessibles via internet ?",["Le cloud","Le cache","Le firewall","Le proxy"],0],
    ["Quelle abréviation désigne un fichier compressé regroupant plusieurs documents ?",["ZIP","GIF","EXE","DNS"],0],
    ["Quel terme désigne une application qui filtre et personnalise les contenus vus par un utilisateur ?",["Un algorithme","Un modem","Un capteur","Un pixel"],0],
    ["Quel terme anglais désigne une personne qui diffuse du contenu en direct sur internet ?",["Un streamer","Un lecteur","Un abonné","Un modérateur"],0],
    ["Quelle abréviation désigne un réseau privé sécurisé permettant de naviguer de façon plus confidentielle ?",["VPN","HTML","URL","USB"],0],
    ["Quel terme désigne une monnaie numérique décentralisée fonctionnant sans banque centrale ?",["La cryptomonnaie","Le crédit","Le forex","L'obligation"],0],
    ["Quel terme désigne la sauvegarde automatique de données sur un support externe ou en ligne ?",["Le backup","Le streaming","Le scrolling","Le mining"],0],
    ["Quelle abréviation désigne un système de gestion de contenu utilisé pour créer des sites web ?",["CMS","GPS","USB","RAM"],0],
    ["Quel terme désigne une extension de navigateur ajoutant une fonctionnalité ?",["Un plugin","Un firmware","Un cookie","Un pixel"],0],
    ["Quel type d'écran équipe la majorité des smartphones modernes pour l'interaction tactile ?",["Un écran tactile","Un écran cathodique","Un écran à aiguilles","Un écran mécanique"],0],
    ["Quelle abréviation désigne un fichier image de haute qualité couramment utilisé sur le web ?",["JPEG","MP3","PDF","ZIP"],0],
    ["Quel terme désigne le fait de publier régulièrement du contenu sur un blog ou une chaîne ?",["Créer du contenu","Formatter un disque","Compiler un code","Router un réseau"],0],
    ["Quel appareil domestique connecté peut répondre à des commandes vocales ?",["Un routeur Wi-Fi","Une enceinte connectée","Un disque dur externe","Un onduleur"],1],
    ["Quel terme désigne un espace de travail numérique partagé accessible depuis plusieurs appareils ?",["Le cloud","Le cache","Le port","Le pare-feu"],0],
    ["Quelle abréviation désigne l'intelligence artificielle générative capable de produire du texte ou des images ?",["IA générative","VPN","GPS","HTML"],0],
    ["Quel terme désigne un contenu qui disparaît automatiquement après 24 heures sur certains réseaux sociaux ?",["Une story","Un tweet","Un post épinglé","Un live permanent"],0],
    ["Quel format vidéo est aujourd'hui un standard courant pour le streaming en ligne ?",["MP4","DOC","XLS","ZIP"],0]
  ],
  history: [
    ["En quelle année débute la Révolution française ?",["1776","1789","1815","1848"],1],
    ["Quel empire avait Rome pour capitale ?",["Empire romain","Empire ottoman","Empire aztèque","Empire du Mali"],0],
    ["Qui a été le premier homme à marcher sur la Lune ?",["Youri Gagarine","Buzz Aldrin","Neil Armstrong","John Glenn"],2],
    ["Quel mur est tombé en 1989 ?",["Mur d’Hadrien","Mur de Berlin","Grande Muraille","Mur des Lamentations"],1],
    ["Quelle civilisation a construit Machu Picchu ?",["Maya","Inca","Romaine","Phénicienne"],1],
    ["Quel roi de France était surnommé le Roi-Soleil ?",["Louis IX","Louis XIV","Henri IV","François Ier"],1],
    ["Dans quel pays les Jeux olympiques antiques sont-ils nés ?",["Italie","Égypte","Grèce","Turquie"],2],
    ["Quel navigateur atteint l’Amérique en 1492 ?",["Magellan","Christophe Colomb","Vasco de Gama","James Cook"],1],
    ["Quelle guerre oppose principalement le Nord et le Sud des États-Unis ?",["Guerre de Sécession","Guerre de Crimée","Guerre des Boers","Guerre de Cent Ans"],0],
    ["Quel peuple a construit les pyramides de Gizeh ?",["Égyptiens antiques","Vikings","Gaulois","Mongols"],0],
    ["Quel événement marque traditionnellement la fin du Moyen Âge ?",["Chute de Constantinople","Bataille de Verdun","Révolution russe","Traité de Rome"],0],
    ["Qui était Jeanne d’Arc ?",["Une reine d’Angleterre","Une figure militaire française","Une scientifique","Une impératrice romaine"],1],
    ["Quel empire était dirigé par Mansa Moussa ?",["Empire du Mali","Empire mongol","Empire byzantin","Empire inca"],0],
    ["Quel conflit mondial se termine en 1945 ?",["Première Guerre mondiale","Seconde Guerre mondiale","Guerre froide","Guerre de Corée"],1],
    ["Quel peuple est associé aux drakkars ?",["Vikings","Samouraïs","Spartiates","Aztèques"],0],
    ["Quelle ville fut ensevelie par le Vésuve en 79 ?",["Pompéi","Athènes","Sparte","Troie"],0],
    ["Quel document anglais de 1215 limite le pouvoir royal ?",["Magna Carta","Code civil","Déclaration de Balfour","Traité de Versailles"],0],
    ["Quel pays a offert la Statue de la Liberté aux États-Unis ?",["Espagne","France","Italie","Canada"],1],
    ["Quel philosophe grec fut le précepteur d'Alexandre le Grand ?",["Socrate","Platon","Aristote","Pythagore"],2],
    ["Quelle bataille de 1815 marque la défaite finale de Napoléon ?",["Austerlitz","Waterloo","Trafalgar","Iéna"],1],
    ["Quel explorateur portugais atteint l'Inde par la mer en 1498 ?",["Christophe Colomb","Vasco de Gama","Fernand de Magellan","Jacques Cartier"],1],
    ["Quel pharaon égyptien est célèbre pour son masque funéraire en or, découvert en 1922 ?",["Ramsès II","Akhenaton","Toutânkhamon","Khéops"],2],
    ["Quel traité met officiellement fin à la Première Guerre mondiale en 1919 ?",["Traité de Vienne","Traité de Westphalie","Traité de Versailles","Traité de Rome"],2],
    ["Quelle reine d'Égypte fut liée à Jules César puis à Marc Antoine ?",["Néfertiti","Cléopâtre","Hatchepsout","Ankhésenamon"],1],
    ["Sur quelle île l'empereur Napoléon Ier mourut-il en exil ?",["L'île d'Elbe","Sainte-Hélène","Corse","Malte"],1],
    ["Quelle ville italienne est considérée comme le berceau de la Renaissance ?",["Venise","Milan","Florence","Naples"],2],
    ["Quel pays a construit la Grande Muraille pour se protéger des invasions ?",["Le Japon","La Chine","La Mongolie","La Corée"],1],
    ["Quel général carthaginois traversa les Alpes avec des éléphants pour attaquer Rome ?",["Hamilcar","Hannibal","Scipion","Hasdrubal"],1],
    ["Quelle guerre antique opposa principalement Athènes et Sparte ?",["La guerre de Troie","Les guerres médiques","La guerre du Péloponnèse","La guerre punique"],2],
    ["Quel document proclame les droits fondamentaux en France en 1789 ?",["Le Code civil","La Déclaration des droits de l'homme et du citoyen","La Constitution de l'an III","L'Édit de Nantes"],1],
    ["Quel roi d'Angleterre est connu pour avoir eu six épouses ?",["Richard Cœur de Lion","Henri VIII","Édouard Ier","Jean sans Terre"],1],
    ["Quelle mission spatiale américaine a permis à l'homme de marcher sur la Lune pour la première fois ?",["Apollo 8","Apollo 11","Gemini 4","Mercury 7"],1],
    ["Quel peuple nomade dirigé par Gengis Khan conquit une grande partie de l'Asie ?",["Les Huns","Les Mongols","Les Turcs","Les Tatars"],1],
    ["Quelle invention est associée au début de la révolution industrielle ?",["L'électricité","La machine à vapeur","Le moteur à combustion","L'imprimerie"],1],
    ["Quel philosophe français a écrit « Du contrat social » ?",["Voltaire","Montesquieu","Jean-Jacques Rousseau","Denis Diderot"],2],
    ["Quelle bataille de 1066 marque la conquête normande de l'Angleterre ?",["La bataille d'Hastings","La bataille de Crécy","La bataille d'Azincourt","La bataille de Bouvines"],0],
    ["Quelle ville fut la capitale de l'Empire byzantin ?",["Rome","Athènes","Constantinople","Alexandrie"],2],
    ["Quel pharaon fit construire le grand temple d'Abou Simbel ?",["Toutânkhamon","Ramsès II","Akhenaton","Thoutmôsis III"],1],
    ["Quel roi de France fut guillotiné en 1793 pendant la Révolution ?",["Louis XV","Louis XVI","Charles X","Louis XVIII"],1],
    ["Quelle civilisation d'Amérique du Sud utilisait des cordelettes à nœuds, les quipus, pour enregistrer des informations ?",["Les Aztèques","Les Mayas","Les Incas","Les Olmèques"],2],
    ["Quel pays a construit le temple d'Angkor Wat ?",["La Thaïlande","Le Cambodge","Le Vietnam","Le Laos"],1],
    ["Quelle civilisation antique a inventé l'écriture cunéiforme ?",["Les Égyptiens","Les Sumériens","Les Phéniciens","Les Perses"],1],
    ["Quel traité de 1648 met fin à la guerre de Trente Ans en Europe ?",["Le traité de Westphalie","Le traité d'Utrecht","Le traité de Tordesillas","Le traité de Vienne"],0],
    ["Quelle reine de France, épouse de Louis XVI, fut surnommée « Madame Déficit » ?",["Anne d'Autriche","Marie de Médicis","Marie-Antoinette","Catherine de Médicis"],2],
    ["Quel pays a lancé le premier satellite artificiel de l'histoire, Spoutnik, en 1957 ?",["Les États-Unis","L'URSS","La France","Le Royaume-Uni"],1],
    ["Quel homme d'État sud-africain, emprisonné pendant 27 ans, devint président en 1994 ?",["Desmond Tutu","Nelson Mandela","Thabo Mbeki","Steve Biko"],1],
    ["Quelle bataille de 1942-1943 marqua un tournant majeur sur le front de l'Est ?",["La bataille de Berlin","La bataille de Koursk","La bataille de Stalingrad","La bataille de Moscou"],2],
    ["Quel explorateur italien a donné indirectement son nom au continent américain ?",["Christophe Colomb","Amerigo Vespucci","Marco Polo","Giovanni Caboto"],1],
    ["Quelle période artistique et intellectuelle suit le Moyen Âge en Europe ?",["Les Lumières","La Renaissance","Le Romantisme","L'Antiquité"],1],
    ["Quel conflit médiéval opposa la France et l'Angleterre pendant plus de cent ans ?",["La guerre des Deux-Roses","La guerre de Cent Ans","La guerre de Succession d'Espagne","La Fronde"],1],
    ["Quel empereur fut couronné à Rome en l'an 800, donnant naissance à l'Empire carolingien ?",["Clovis","Charlemagne","Charles Martel","Pépin le Bref"],1],
    ["Quel savant italien fut jugé par l'Église pour avoir défendu que la Terre tourne autour du Soleil ?",["Copernic","Galilée","Kepler","Newton"],1],
    ["Quel document fondateur des États-Unis fut signé en 1776 ?",["La Constitution américaine","La Déclaration d'indépendance","Le Bill of Rights","Le traité de Paris"],1],
    ["Sous l'impulsion de quel chancelier l'Allemagne fut-elle unifiée en 1871 ?",["Guillaume II","Otto von Bismarck","Metternich","Adolf Hitler"],1],
    ["Quelle épidémie du 14e siècle décima une grande partie de la population européenne ?",["Le choléra","La grippe espagnole","La peste noire","La variole"],2],
    ["Quel physicien est célèbre pour sa théorie de la relativité ?",["Isaac Newton","Albert Einstein","Niels Bohr","Max Planck"],1],
    ["Quel roi anglais accepta la Magna Carta en 1215, limitant le pouvoir royal ?",["Richard Cœur de Lion","Jean sans Terre","Henri II","Édouard Ier"],1],
    ["Quel empire avait pour capitale Constantinople avant sa chute en 1453 ?",["L'Empire ottoman","L'Empire byzantin","L'Empire perse","L'Empire romain d'Occident"],1]
  ],
  cinema: [
    ["Qui a réalisé Titanic ?",["Steven Spielberg","James Cameron","Christopher Nolan","Ridley Scott"],1],
    ["Dans quelle série trouve-t-on Walter White ?",["Narcos","Breaking Bad","Ozark","Lost"],1],
    ["Quel film met en scène Dark Vador ?",["Star Trek","Star Wars","Dune","Avatar"],1],
    ["Qui interprète Harry Potter au cinéma ?",["Daniel Radcliffe","Rupert Grint","Tom Holland","Elijah Wood"],0],
    ["Dans Friends, quel est le prénom de la sœur de Monica ?",["Rachel","Phoebe","Ross","Emily"],2],
    ["Qui a réalisé Jurassic Park (1993) ?",["George Lucas","Steven Spielberg","James Cameron","Ridley Scott"],1],
    ["Quel film Disney raconte l'histoire d'un lion nommé Simba devant reconquérir sa place de roi ?",["Le Livre de la jungle","Tarzan","Le Roi Lion","Bambi"],2],
    ["Quel acteur interprète Iron Man dans l'univers cinématographique Marvel ?",["Chris Evans","Robert Downey Jr.","Chris Hemsworth","Mark Ruffalo"],1],
    ["Quel réalisateur est connu pour Pulp Fiction ?",["Martin Scorsese","Quentin Tarantino","David Fincher","Guy Ritchie"],1],
    ["Quel film met en scène un homme au destin extraordinaire nommé Forrest Gump ?",["Forrest Gump","Rain Man","Big Fish","The Truman Show"],0],
    ["Quel acteur incarne le capitaine Jack Sparrow dans Pirates des Caraïbes ?",["Orlando Bloom","Johnny Depp","Geoffrey Rush","Javier Bardem"],1],
    ["Quel studio d'animation a créé la saga Toy Story ?",["DreamWorks","Pixar","Illumination","Blue Sky Studios"],1],
    ["Quel réalisateur a mis en scène la trilogie du Seigneur des Anneaux ?",["Peter Jackson","Guillermo del Toro","James Cameron","Ang Lee"],0],
    ["Quel film raconte le naufrage d'un paquebot après avoir heurté un iceberg en 1912 ?",["Titanic","Le Poséidon","La Traversée","L'Odyssée"],0],
    ["Quel super-héros est surnommé « l'Homme chauve-souris » ?",["Superman","Batman","Flash","Green Lantern"],1],
    ["Dans quelle saga trouve-t-on le personnage Yoda ?",["Star Trek","Star Wars","Dune","Le Seigneur des Anneaux"],1],
    ["Quel réalisateur a mis en scène Inception et Interstellar ?",["Denis Villeneuve","Christopher Nolan","Ridley Scott","Alfonso Cuarón"],1],
    ["Quel dessin animé Disney met en scène une sirène nommée Ariel ?",["La Petite Sirène","Vaiana","Pocahontas","Raiponce"],0],
    ["Quel acteur interprète Neo dans la trilogie Matrix ?",["Keanu Reeves","Will Smith","Tom Cruise","Brad Pitt"],0],
    ["Quelle actrice incarne Hermione Granger dans la saga Harry Potter ?",["Emma Stone","Emma Watson","Emma Thompson","Emma Roberts"],1],
    ["Quel réalisateur a créé la saga Star Wars ?",["Steven Spielberg","George Lucas","James Cameron","J.J. Abrams"],1],
    ["Quel film met en scène un requin terrorisant une station balnéaire (1975) ?",["Les Dents de la mer","Piranha","Open Water","Deep Blue Sea"],0],
    ["Quel super-héros porte un costume rouge et bleu et tisse des toiles ?",["Daredevil","Spider-Man","Ant-Man","Nightwing"],1],
    ["Quel film Disney raconte l'histoire d'Elsa et Anna dans un royaume enneigé ?",["Frozen (La Reine des neiges)","Raiponce","Vaiana","Encanto"],0],
    ["Quel acteur incarne le Joker dans The Dark Knight (2008) ?",["Jared Leto","Heath Ledger","Joaquin Phoenix","Jack Nicholson"],1],
    ["Quelle actrice interprète Katniss Everdeen dans Hunger Games ?",["Emma Watson","Jennifer Lawrence","Kristen Stewart","Shailene Woodley"],1],
    ["Quel film sorti en 2001 raconte la première année d'un jeune sorcier à Poudlard ?",["Harry Potter à l'école des sorciers","Le Monde de Narnia","Percy Jackson","Eragon"],0],
    ["Quel réalisateur a mis en scène Shining (1980) ?",["Stanley Kubrick","Alfred Hitchcock","Wes Craven","John Carpenter"],0],
    ["Quel film Pixar met en scène un poisson-clown parti à la recherche de son fils ?",["Le Monde de Nemo","Vice-Versa","Rebelle","Coco"],0],
    ["Quel acteur incarne James Bond dans Skyfall et Spectre ?",["Pierce Brosnan","Daniel Craig","Sean Connery","Roger Moore"],1],
    ["Quel film met en scène un extraterrestre voulant rentrer chez lui grâce à un enfant ?",["E.T. l'extra-terrestre","Rencontres du troisième type","La Guerre des mondes","District 9"],0],
    ["Quelle franchise met en scène des courses de voitures et des braquages spectaculaires ?",["Need for Speed","Fast and Furious","Drive","Baby Driver"],1],
    ["Quel personnage Disney perd sa pantoufle de verre à minuit ?",["Blanche-Neige","Cendrillon","La Belle au bois dormant","Raiponce"],1],
    ["Quel personnage d'animation est un ogre vert vivant dans un marais ?",["Shrek","Hulk","Fiona","Donkey"],0],
    ["Quelle actrice incarne Black Widow dans les films Marvel ?",["Elizabeth Olsen","Scarlett Johansson","Brie Larson","Zoe Saldana"],1],
    ["Quel film Pixar met en scène un robot resté seul à nettoyer une Terre abandonnée ?",["Wall-E","Big Hero 6","Les Indestructibles","Ratatouille"],0],
    ["Quel acteur incarne Wolverine dans les films X-Men ?",["Hugh Jackman","Patrick Stewart","Ian McKellen","James McAvoy"],0],
    ["Quel réalisateur est à l'origine du film Alien, le huitième passager (1979) ?",["James Cameron","Ridley Scott","John Carpenter","David Fincher"],1],
    ["Quel réalisateur est le créateur de la saga Indiana Jones aux côtés de George Lucas ?",["Steven Spielberg","Robert Zemeckis","Ron Howard","Brian De Palma"],0],
    ["Quel super-héros porte un bouclier et un costume aux couleurs du drapeau américain ?",["Iron Man","Captain America","Thor","Hawkeye"],1],
    ["Quel film Disney met en scène un renard et un chien devenus amis malgré leur nature ?",["Rox et Rouky","Les 101 Dalmatiens","La Belle et le Clochard","Bernard et Bianca"],0],
    ["Quel personnage Disney possède une lampe magique abritant un génie ?",["Sinbad","Aladdin","Ali Baba","Le Prince Ahmed"],1],
    ["Quel acteur incarne Thor dans les films Marvel ?",["Chris Hemsworth","Chris Evans","Chris Pratt","Chris Pine"],0],
    ["Quel réalisateur français a signé Le Fabuleux Destin d'Amélie Poulain (2001) ?",["Luc Besson","Jean-Pierre Jeunet","Michel Gondry","Claude Lelouch"],1],
    ["Quel film de 2012 réunit pour la première fois les super-héros Marvel au sein d'une même équipe ?",["Avengers","Captain America : Civil War","Iron Man 2","X-Men"],0],
    ["Quel dessin animé Disney met en scène des animaux de la jungle dont un ours nommé Baloo ?",["Le Livre de la jungle","Tarzan","Le Roi Lion","Frère des ours"],0],
    ["Quel personnage Disney est un pirate ayant une main remplacée par un crochet ?",["Barbe Noire","Le capitaine Crochet","Long John Silver","Jack Sparrow"],1],
    ["Quel acteur a prêté sa voix (en version originale) au personnage Woody dans Toy Story ?",["Tom Hanks","Tim Allen","Billy Crystal","Tom Cruise"],0]
  ],
  sport: [
    ["Tous les combien d’années ont lieu les Jeux olympiques d’été ?",["2 ans","4 ans","5 ans","6 ans"],1],
    ["Combien de joueurs compte une équipe de basket-ball sur le terrain ?",["4","5","6","7"],1],
    ["Dans quel sport parle-t-on de « grand chelem » ?",["Golf","Tennis","Rugby","Cyclisme"],1],
    ["Combien de temps dure un match de football (temps réglementaire) ?",["60 minutes","70 minutes","90 minutes","120 minutes"],2],
    ["Quel pays a inventé le rugby ?",["France","Angleterre","Nouvelle-Zélande","Afrique du Sud"],1],
    ["Combien d’anneaux compte le symbole olympique ?",["4","5","6","7"],1],
    ["Dans quel sport utilise-t-on un « ippon » ?",["Judo","Escrime","Boxe","Karaté"],0],
    ["Quelle discipline regroupe le 100 m, le saut en longueur et le lancer de poids ?",["Le décathlon","Le pentathlon","L’heptathlon","Le triathlon"],0],
    ["Combien de sets faut-il gagner pour remporter un match de tennis en 5 sets ?",["2","3","4","5"],1],
    ["Quel est le nombre de joueurs d’une équipe de volley-ball sur le terrain ?",["5","6","7","8"],1],
    ["Combien de temps dure une mi-temps au football ?",["30 minutes","45 minutes","50 minutes","60 minutes"],1],
    ["Quel pays a remporté la Coupe du monde de football en 2018 ?",["Croatie","Belgique","France","Angleterre"],2],
    ["Quel sport se joue avec une raquette et un volant ?",["Le tennis","Le squash","Le badminton","Le ping-pong"],2],
    ["Combien de joueurs une équipe de rugby à XV aligne-t-elle sur le terrain ?",["11","13","15","17"],2],
    ["Dans quel sport marque-t-on des points en réalisant un « essai » ?",["Le football américain","Le rugby","Le hockey","Le handball"],1],
    ["Quel pays est considéré comme le berceau du judo ?",["La Chine","La Corée","Le Japon","La Thaïlande"],2],
    ["Combien de trous compte un parcours de golf classique ?",["9","18","24","36"],1],
    ["Quel sport combine natation, cyclisme et course à pied ?",["Le pentathlon","Le triathlon","Le décathlon","L'heptathlon"],1],
    ["Quelle distance représente approximativement un marathon ?",["21 km","32 km","42 km","50 km"],2],
    ["Quel pays a remporté le plus grand nombre de Coupes du monde de football à ce jour ?",["Allemagne","Argentine","Italie","Brésil"],3],
    ["Sur quelle surface se joue traditionnellement le tournoi de tennis de Roland-Garros ?",["Le gazon","La terre battue","Le ciment","Le synthétique"],1],
    ["Sur quelle surface se joue traditionnellement le tournoi de tennis de Wimbledon ?",["La terre battue","Le gazon","Le ciment","Le carpet"],1],
    ["Dans quel pays se déroule le tournoi de tennis de Roland-Garros ?",["Angleterre","Australie","France","États-Unis"],2],
    ["Combien de rondes compte au maximum un combat de boxe professionnelle standard ?",["8","10","12","15"],2],
    ["Quel pays est à l'origine du tennis moderne au XIXe siècle ?",["La France","L'Angleterre","Les États-Unis","L'Espagne"],1],
    ["Dans quel sport les joueurs utilisent-ils une crosse pour faire glisser un palet sur la glace ?",["Le curling","Le hockey sur glace","Le patinage artistique","Le bobsleigh"],1],
    ["Combien de joueurs une équipe de handball aligne-t-elle sur le terrain ?",["5","6","7","8"],2],
    ["Quel sport nautique consiste à glisser sur l'eau en étant tracté par un bateau ?",["La voile","Le ski nautique","L'aviron","Le canoë"],1],
    ["Quel pays a remporté la Coupe du monde de rugby en 2019 ?",["Nouvelle-Zélande","Angleterre","Afrique du Sud","Pays de Galles"],2],
    ["Quel athlète jamaïcain a dominé les épreuves de sprint mondial dans les années 2010 ?",["Usain Bolt","Yohan Blake","Justin Gatlin","Tyson Gay"],0],
    ["Combien de joueurs une équipe de water-polo aligne-t-elle dans l'eau ?",["6","7","8","9"],1],
    ["Quel sport de combat japonais voit son nom signifier littéralement « voie douce » ?",["Le karaté","Le judo","L'aïkido","Le sumo"],1],
    ["Quel sport de raquette se pratique dans une salle fermée entourée de quatre murs ?",["Le squash","Le padel","Le tennis","Le badminton"],0],
    ["Quel pays est à l'origine du baseball moderne ?",["Le Canada","Le Japon","Les États-Unis","Cuba"],2],
    ["Quel terme désigne, au golf, un score d'un coup sous le par sur un trou ?",["Un birdie","Un bogey","Un albatros","Un eagle"],0],
    ["Quelle célèbre course cycliste se déroule chaque été en France ?",["Le Giro","La Vuelta","Le Tour de France","Paris-Roubaix"],2],
    ["Quel sport d'hiver associe le ski de fond et le tir à la carabine ?",["Le combiné nordique","Le biathlon","Le ski alpin","Le saut à ski"],1],
    ["Combien de temps dure un quart-temps en NBA (basket-ball américain) ?",["10 minutes","12 minutes","15 minutes","20 minutes"],1],
    ["Quel pays a remporté le plus de médailles d'or aux Jeux olympiques d'été au cours de leur histoire ?",["Chine","Russie","États-Unis","Royaume-Uni"],2],
    ["Quelle nage est considérée comme la plus rapide en compétition de natation ?",["La brasse","Le dos crawlé","Le crawl","Le papillon"],2],
    ["Quel pays a organisé les premiers Jeux olympiques modernes en 1896 ?",["La France","La Grèce","L'Italie","Le Royaume-Uni"],1],
    ["Quel est le nombre de manches (sets) à remporter pour gagner un match de volley-ball classique en 5 sets ?",["2","3","4","5"],1],
    ["Quel sport se joue traditionnellement avec des quilles que l'on doit toutes faire tomber d'un coup ?",["Le bowling","Le curling","Le billard","Le golf"],0],
    ["Quel sport voit deux équipes de 11 joueurs s'affronter autour d'un ballon rond ?",["Le rugby","Le football","Le football américain","Le hockey"],1],
    ["Quel équipement protège la tête des cyclistes et des motards ?",["Le casque","Les gants","Les protège-tibias","La visière"],0],
    ["Quel sport olympique voit les athlètes s'affronter à l'épée, au fleuret ou au sabre ?",["Le tir à l'arc","L'escrime","Le pentathlon","Le judo"],1],
    ["Quel équipement est obligatoire pour un gardien de but au football pour se distinguer de ses coéquipiers ?",["Un brassard","Un maillot de couleur différente","Des gants renforcés","Un casque"],1],
    ["Quel pays a inventé le cricket ?",["L'Inde","L'Australie","L'Angleterre","L'Afrique du Sud"],2],
    ["Quel sport se pratique sur une piste ovale avec des vélos sans freins ni vitesses ?",["Le BMX","Le cyclisme sur piste","Le VTT","Le cyclo-cross"],1]
  ],
  animals: [
    ["Quel est le plus rapide des animaux terrestres ?",["Lion","Guépard","Gazelle","Antilope"],1],
    ["Combien de cœurs possède une pieuvre ?",["1","2","3","4"],2],
    ["Quel est le seul mammifère capable de voler ?",["L’écureuil volant","La chauve-souris","Le colibri","Le flying fox"],1],
    ["Quel animal est réputé pour sa mémoire exceptionnelle ?",["Éléphant","Mouton","Poule","Lapin"],0],
    ["Quel oiseau est incapable de voler et vit en Antarctique ?",["Autruche","Manchot","Pélican","Flamant rose"],1],
    ["De quel continent le kangourou est-il originaire ?",["Afrique","Asie","Océanie","Amérique du Sud"],2],
    ["Quel est le plus grand animal terrestre actuel ?",["Rhinocéros","Hippopotame","Éléphant d’Afrique","Girafe"],2],
    ["Combien de pattes possède une araignée ?",["6","8","10","12"],1],
    ["Quel animal change de couleur pour se camoufler ?",["Le caméléon","Le hérisson","Le castor","Le renard"],0],
    ["Quel est le nom du bébé du kangourou ?",["Faon","Joey","Poussin","Chiot"],1],
    ["Quel est le plus grand oiseau vivant, par la taille ?",["Le condor","L'aigle royal","L'autruche","Le pélican"],2],
    ["Quel animal marin est considéré comme le plus grand du monde ?",["Le requin baleine","La baleine bleue","L'orque","Le cachalot"],1],
    ["Quel mammifère australien pond des œufs au lieu de donner naissance à des petits ?",["Le koala","Le wombat","L'ornithorynque","Le diable de Tasmanie"],2],
    ["Combien de mois dure environ la gestation d'un éléphant ?",["9 mois","14 mois","22 mois","30 mois"],2],
    ["Quel reptile est capable de faire repousser sa queue s'il la perd ?",["Le crocodile","Le lézard","La tortue","Le serpent"],1],
    ["Quel est le plus grand serpent du monde en longueur, pouvant dépasser 6 mètres ?",["Le python réticulé","La vipère","Le boa constrictor","Le cobra royal"],0],
    ["Quel oiseau est capable de voler à reculons ?",["Le moineau","Le colibri","L'aigle","Le pigeon"],1],
    ["Quel animal possède des rayures aussi uniques qu'une empreinte digitale ?",["Le tigre","Le zèbre","Le guépard","Le lémurien"],1],
    ["Quel type d'animal est la grenouille, capable de vivre dans l'eau et sur terre ?",["Un reptile","Un amphibien","Un mammifère","Un poisson"],1],
    ["Quel animal africain possède un long cou lui permettant d'atteindre les feuilles des arbres élevés ?",["L'éléphant","Le zèbre","La girafe","Le buffle"],2],
    ["Quel animal marin possède huit bras et peut changer de couleur pour se camoufler ?",["La pieuvre","L'étoile de mer","La méduse","Le crabe"],0],
    ["Quel insecte produit du miel dans une ruche ?",["La guêpe","La fourmi","L'abeille","Le bourdon"],2],
    ["Comment appelle-t-on le cri du lion ?",["Le hennissement","Le rugissement","Le beuglement","Le barrissement"],1],
    ["Quel animal, symbole de la Chine, se nourrit presque exclusivement de bambou ?",["Le panda roux","Le panda géant","L'ours noir d'Asie","Le koala"],1],
    ["Quel animal marin est en réalité un mammifère malgré son mode de vie aquatique ?",["Le requin","Le dauphin","La raie","La murène"],1],
    ["Combien de paires de cœurs possède approximativement un ver de terre ?",["1","3","5","10"],2],
    ["Quel poisson est connu pour pouvoir changer de sexe au cours de sa vie ?",["Le poisson-clown","Le saumon","Le thon","La truite"],0],
    ["Quel est le rapace réputé pour être l'animal le plus rapide en vol piqué ?",["L'aigle royal","Le faucon pèlerin","Le vautour","Le milan"],1],
    ["Quel animal terrestre a l'espérance de vie la plus longue parmi les mammifères ?",["Le rhinocéros","La girafe","L'éléphant","Le buffle"],2],
    ["Quel oiseau est réputé pour imiter la voix humaine et d'autres sons ?",["Le corbeau","Le perroquet","Le pigeon","Le moineau"],1],
    ["Quel animal est considéré comme le plus proche parent génétique de l'être humain ?",["Le gorille","L'orang-outan","Le chimpanzé","Le babouin"],2],
    ["Quel animal possède une carapace qui fait partie intégrante de son squelette ?",["Le crabe","La tortue","L'escargot","Le tatou"],1],
    ["Quel mammifère marin est réputé dormir avec seulement la moitié de son cerveau à la fois ?",["La baleine","Le dauphin","Le phoque","Le lamantin"],1],
    ["Quel est le plus grand félin du monde par la taille et le poids ?",["Le lion","Le tigre","Le jaguar","Le léopard"],1],
    ["Quel animal australien est capable de sauter sur de très grandes distances malgré sa petite taille ?",["Le wombat","Le kangourou","Le koala","Le diable de Tasmanie"],1],
    ["Quel oiseau incapable de voler est le symbole national de la Nouvelle-Zélande ?",["L'émeu","Le kiwi","Le manchot","Le nandou"],1],
    ["Quel animal produit de la soie pour tisser sa toile ?",["Le ver à soie","L'araignée","La chenille","Le scarabée"],1],
    ["Quel mammifère est capable de planer grâce à un repli de peau, sans être une chauve-souris ?",["L'écureuil volant","Le lémurien","Le opossum","Le renard volant"],0],
    ["Quel animal marin possède un exosquelette et se déplace généralement de côté ?",["La crevette","Le crabe","L'oursin","La moule"],1],
    ["Quel oiseau migrateur parcourt la plus grande distance chaque année, selon les records connus ?",["L'hirondelle","La cigogne","La sterne arctique","L'albatros"],2],
    ["Quel animal marin est capable de régénérer entièrement son corps à partir d'un fragment ?",["La méduse","L'étoile de mer","Le poulpe","L'anémone"],1],
    ["Quel animal domestique descend directement du loup gris ?",["Le chat","Le chien","Le furet","Le lapin"],1],
    ["Quel est le plus petit oiseau du monde ?",["Le moineau","Le roitelet","Le colibri abeille","La mésange"],2],
    ["Quel animal marin filtre l'eau de mer pour se nourrir de plancton malgré sa taille immense ?",["Le requin blanc","La baleine bleue","L'orque","Le thon rouge"],1],
    ["Quel animal est réputé pour sa mémoire visuelle et sa capacité à reconnaître son reflet dans un miroir ?",["Le chat","L'éléphant","Le lapin","Le hamster"],1],
    ["Quel oiseau aquatique niche en immenses colonies en Antarctique et ne vole pas ?",["Le pélican","Le manchot","Le cormoran","L'albatros"],1],
    ["Quel animal est capable de dormir debout, y compris parfois en marchant ?",["Le cheval","Le chien","Le chat","Le lapin"],0],
    ["Quel animal possède la langue la plus longue par rapport à sa taille corporelle ?",["Le caméléon","La girafe","Le fourmilier","La grenouille"],0],
    ["Quel petit mammifère marin, cousin du lamantin, vit dans les eaux chaudes de l'océan Indien et du Pacifique ?",["Le phoque","Le dugong","La loutre de mer","L'otarie"],1]
  ],
  capitals: [
    ["Quel pays a pour capitale Kaboul ?",["Afghanistan","Liberia","Mexique","Costa Rica"],0],
    ["Quel pays a pour capitale Pretoria ?",["Allemagne","Ouzbékistan","Rwanda","Afrique du Sud"],3],
    ["Quel pays a pour capitale Tirana ?",["Tunisie","Albanie","Singapour","Irak"],1],
    ["Quel pays a pour capitale Alger ?",["Italie","Algérie","Géorgie","Tunisie"],1],
    ["Quel pays a pour capitale Berlin ?",["Allemagne","Liban","Costa Rica","Gambie"],0],
    ["Quel pays a pour capitale Andorre-la-Vieille ?",["Pologne","Tadjikistan","Andorre","Estonie"],2],
    ["Quel pays a pour capitale Luanda ?",["Ouzbékistan","Bangladesh","Bahamas","Angola"],3],
    ["Quel pays a pour capitale Riyad ?",["Arabie saoudite","Tchad","Congo (RDC)","Turkménistan"],0],
    ["Quel pays a pour capitale Buenos Aires ?",["Ouganda","Argentine","Guinée-Bissau","Djibouti"],1],
    ["Quel pays a pour capitale Erevan ?",["Cap-Vert","Émirats arabes unis","Arménie","Tuvalu"],2],
    ["Quel pays a pour capitale Canberra ?",["Bosnie-Herzégovine","Australie","Slovaquie","Liban"],1],
    ["Quel pays a pour capitale Vienne ?",["Autriche","République dominicaine","Soudan","Micronésie"],0],
    ["Quel pays a pour capitale Bakou ?",["Éthiopie","Maurice","Kirghizistan","Azerbaïdjan"],3],
    ["Quel pays a pour capitale Nassau ?",["Bahamas","Slovénie","Thaïlande","Chine"],0],
    ["Quel pays a pour capitale Manama ?",["Eswatini","Bahreïn","Suriname","Maroc"],1],
    ["Quel pays a pour capitale Dacca ?",["Bangladesh","Autriche","Chine","Costa Rica"],0],
    ["Quel pays a pour capitale Bruxelles ?",["Belgique","Finlande","Cambodge","Liberia"],0],
    ["Quel pays a pour capitale Belmopan ?",["Bénin","Belize","Comores","Djibouti"],1],
    ["Quel pays a pour capitale Porto-Novo ?",["Norvège","Kenya","Malaisie","Bénin"],3],
    ["Quel pays a pour capitale Thimphou ?",["Bhoutan","Suriname","République centrafricaine","Panama"],0],
    ["Quel pays a pour capitale Minsk ?",["Vietnam","Biélorussie","Bolivie","Népal"],1],
    ["Quel pays a pour capitale Naypyidaw ?",["Birmanie (Myanmar)","Ghana","Moldavie","Panama"],0],
    ["Quel pays a pour capitale Sucre ?",["Bolivie","Chili","Syrie","Islande"],0],
    ["Quel pays a pour capitale Sarajevo ?",["Soudan","Autriche","Bosnie-Herzégovine","Philippines"],2],
    ["Quel pays a pour capitale Gaborone ?",["Émirats arabes unis","Jordanie","Monténégro","Botswana"],3],
    ["Quel pays a pour capitale Brasilia ?",["Côte d’Ivoire","Biélorussie","Brésil","Zimbabwe"],2],
    ["Quel pays a pour capitale Bandar Seri Begawan ?",["Brunei","Belize","Mexique","Koweït"],0],
    ["Quel pays a pour capitale Sofia ?",["Monaco","Corée du Sud","Bulgarie","Liban"],2],
    ["Quel pays a pour capitale Ouagadougou ?",["Samoa","Burundi","Burkina Faso","Bosnie-Herzégovine"],2],
    ["Quel pays a pour capitale Gitega ?",["Tuvalu","Allemagne","Burundi","Lettonie"],2],
    ["Quel pays a pour capitale Phnom Penh ?",["Togo","Cambodge","Maldives","Cuba"],1],
    ["Quel pays a pour capitale Yaoundé ?",["Tadjikistan","Afrique du Sud","Mauritanie","Cameroun"],3],
    ["Quel pays a pour capitale Ottawa ?",["Canada","Roumanie","Philippines","Honduras"],0],
    ["Quel pays a pour capitale Praia ?",["Cap-Vert","Costa Rica","Vatican","Maroc"],0],
    ["Quel pays a pour capitale Santiago ?",["Chili","Suède","Biélorussie","Nigéria"],0],
    ["Quel pays a pour capitale Pékin ?",["Irlande","Cuba","Salvador","Chine"],3],
    ["Quel pays a pour capitale Nicosie ?",["États-Unis","Chypre","République tchèque","Bahreïn"],1],
    ["Quel pays a pour capitale Bogota ?",["Birmanie (Myanmar)","Bolivie","Nauru","Colombie"],3],
    ["Quel pays a pour capitale Moroni ?",["Afrique du Sud","Congo (Brazzaville)","Comores","Bulgarie"],2],
    ["Quel pays a pour capitale Brazzaville ?",["Congo (Brazzaville)","Liban","Andorre","Chine"],0],
    ["Quel pays a pour capitale Kinshasa ?",["Nicaragua","Congo (RDC)","Angola","Sao Tomé-et-Principe"],1],
    ["Quel pays a pour capitale Pyongyang ?",["Corée du Nord","Tunisie","Botswana","Chili"],0],
    ["Quel pays a pour capitale Séoul ?",["Bulgarie","Timor oriental","Suède","Corée du Sud"],3],
    ["Quel pays a pour capitale San José ?",["Costa Rica","Kosovo","Madagascar","Bangladesh"],0],
    ["Quel pays a pour capitale Yamoussoukro ?",["Lettonie","Côte d’Ivoire","Tchad","Allemagne"],1],
    ["Quel pays a pour capitale Zagreb ?",["Samoa","Iran","Croatie","Mexique"],2],
    ["Quel pays a pour capitale La Havane ?",["Guatemala","Slovaquie","Kirghizistan","Cuba"],3],
    ["Quel pays a pour capitale Copenhague ?",["Angola","Belgique","Danemark","Bhoutan"],2],
    ["Quel pays a pour capitale Djibouti ?",["Djibouti","Salvador","Mali","Portugal"],0],
    ["Quel pays a pour capitale Le Caire ?",["Égypte","Tadjikistan","Nicaragua","Gabon"],0],
    ["Quel pays a pour capitale Abou Dabi ?",["Tonga","Émirats arabes unis","France","Belize"],1],
    ["Quel pays a pour capitale Quito ?",["Koweït","Sao Tomé-et-Principe","Malawi","Équateur"],3],
    ["Quel pays a pour capitale Asmara ?",["Soudan","Albanie","Érythrée","Haïti"],2],
    ["Quel pays a pour capitale Madrid ?",["Mauritanie","Congo (Brazzaville)","Espagne","Luxembourg"],2],
    ["Quel pays a pour capitale Tallinn ?",["Estonie","Bangladesh","Turkménistan","Sénégal"],0],
    ["Quel pays a pour capitale Mbabane ?",["Eswatini","Tchad","Trinité-et-Tobago","Érythrée"],0],
    ["Quel pays a pour capitale Washington ?",["République centrafricaine","Chili","Liberia","États-Unis"],3],
    ["Quel pays a pour capitale Addis-Abeba ?",["Qatar","Congo (RDC)","Éthiopie","Norvège"],2],
    ["Quel pays a pour capitale Suva ?",["Fidji","Kazakhstan","Vatican","Burundi"],0],
    ["Quel pays a pour capitale Helsinki ?",["Finlande","Bolivie","Norvège","Libye"],0],
    ["Quel pays a pour capitale Paris ?",["Biélorussie","Mozambique","France","Estonie"],2],
    ["Quel pays a pour capitale Libreville ?",["Gabon","Arménie","Mali","Palaos"],0],
    ["Quel pays a pour capitale Banjul ?",["Gambie","Cameroun","Népal","Haïti"],0],
    ["Quel pays a pour capitale Tbilissi ?",["Géorgie","Islande","Togo","Belgique"],0],
    ["Quel pays a pour capitale Accra ?",["Indonésie","République tchèque","Ghana","Mozambique"],2],
    ["Quel pays a pour capitale Athènes ?",["Biélorussie","Azerbaïdjan","Grèce","Bolivie"],2],
    ["Quel pays a pour capitale Guatemala ?",["Paraguay","Bulgarie","Guatemala","Norvège"],2],
    ["Quel pays a pour capitale Conakry ?",["Nicaragua","Guinée","Émirats arabes unis","Turquie"],1],
    ["Quel pays a pour capitale Malabo ?",["Chili","Guinée équatoriale","Kiribati","Australie"],1],
    ["Quel pays a pour capitale Bissau ?",["France","Guinée-Bissau","Malte","Moldavie"],1],
    ["Quel pays a pour capitale Georgetown ?",["Serbie","Djibouti","Macédoine du Nord","Guyana"],3],
    ["Quel pays a pour capitale Port-au-Prince ?",["Côte d’Ivoire","Islande","Haïti","Costa Rica"],2],
    ["Quel pays a pour capitale Tegucigalpa ?",["Honduras","Sierra Leone","Chypre","Pologne"],0],
    ["Quel pays a pour capitale Budapest ?",["Hongrie","Égypte","Sénégal","Serbie"],0],
    ["Quel pays a pour capitale New Delhi ?",["Inde","Chypre","Albanie","Estonie"],0],
    ["Quel pays a pour capitale Jakarta ?",["Salomon (Îles)","Honduras","Indonésie","Belgique"],2],
    ["Quel pays a pour capitale Bagdad ?",["Nauru","Estonie","Irak","Burkina Faso"],2],
    ["Quel pays a pour capitale Téhéran ?",["Nauru","Iran","Bhoutan","Équateur"],1],
    ["Quel pays a pour capitale Dublin ?",["Émirats arabes unis","Djibouti","Micronésie","Irlande"],3],
    ["Quel pays a pour capitale Reykjavik ?",["Jordanie","Azerbaïdjan","Érythrée","Islande"],3],
    ["Quel pays a pour capitale Jérusalem ?",["Turkménistan","Israël","Bolivie","Nigéria"],1],
    ["Quel pays a pour capitale Rome ?",["Danemark","Jamaïque","Tunisie","Italie"],3],
    ["Quel pays a pour capitale Kingston ?",["Jamaïque","Mongolie","Maldives","Ouganda"],0],
    ["Quel pays a pour capitale Tokyo ?",["Japon","Lituanie","Trinité-et-Tobago","République dominicaine"],0],
    ["Quel pays a pour capitale Amman ?",["Nigéria","Monaco","Libye","Jordanie"],3],
    ["Quel pays a pour capitale Astana ?",["Mauritanie","Slovaquie","Monaco","Kazakhstan"],3],
    ["Quel pays a pour capitale Nairobi ?",["Kenya","Équateur","Andorre","Soudan du Sud"],0],
    ["Quel pays a pour capitale Bichkek ?",["Guinée-Bissau","Corée du Sud","Kirghizistan","Japon"],2],
    ["Quel pays a pour capitale Tarawa-Sud ?",["Malte","Lettonie","Samoa","Kiribati"],3],
    ["Quel pays a pour capitale Pristina ?",["Kosovo","Bhoutan","Niger","Danemark"],0],
    ["Quel pays a pour capitale Koweït City ?",["Koweït","Arabie saoudite","Yémen","Sri Lanka"],0],
    ["Quel pays a pour capitale Vientiane ?",["Marshall (Îles)","Laos","Ouzbékistan","Maroc"],1],
    ["Quel pays a pour capitale Maseru ?",["Érythrée","Suisse","Lesotho","Honduras"],2],
    ["Quel pays a pour capitale Riga ?",["Grèce","Lettonie","Paraguay","Tunisie"],1],
    ["Quel pays a pour capitale Beyrouth ?",["Argentine","Tanzanie","Kiribati","Liban"],3],
    ["Quel pays a pour capitale Monrovia ?",["Slovaquie","Niger","Autriche","Liberia"],3],
    ["Quel pays a pour capitale Tripoli ?",["Zimbabwe","Libye","Argentine","Brunei"],1],
    ["Quel pays a pour capitale Vaduz ?",["Érythrée","Paraguay","Liechtenstein","Salvador"],2],
    ["Quel pays a pour capitale Vilnius ?",["Tanzanie","France","Kosovo","Lituanie"],3],
    ["Quel pays a pour capitale Luxembourg ?",["Sierra Leone","Bahamas","Luxembourg","Roumanie"],2],
    ["Quel pays a pour capitale Skopje ?",["Arabie saoudite","France","Liberia","Macédoine du Nord"],3],
    ["Quel pays a pour capitale Antananarivo ?",["Madagascar","Portugal","Mongolie","Oman"],0],
    ["Quel pays a pour capitale Kuala Lumpur ?",["Togo","Djibouti","Liechtenstein","Malaisie"],3],
    ["Quel pays a pour capitale Lilongwe ?",["Irak","Rwanda","Malawi","Togo"],2],
    ["Quel pays a pour capitale Malé ?",["Indonésie","Honduras","Maldives","Lettonie"],2],
    ["Quel pays a pour capitale Bamako ?",["Mali","Marshall (Îles)","Salvador","Burkina Faso"],0],
    ["Quel pays a pour capitale La Valette ?",["Cambodge","Chypre","Royaume-Uni","Malte"],3],
    ["Quel pays a pour capitale Rabat ?",["Nouvelle-Zélande","Thaïlande","Saint-Marin","Maroc"],3],
    ["Quel pays a pour capitale Majuro ?",["Marshall (Îles)","Congo (Brazzaville)","Niger","Vanuatu"],0],
    ["Quel pays a pour capitale Port-Louis ?",["Sénégal","Tuvalu","Maurice","Jamaïque"],2],
    ["Quel pays a pour capitale Nouakchott ?",["Mauritanie","Fidji","Lesotho","Kazakhstan"],0],
    ["Quel pays a pour capitale Mexico ?",["États-Unis","Congo (Brazzaville)","Mexique","Maldives"],2],
    ["Quel pays a pour capitale Palikir ?",["États-Unis","Danemark","Micronésie","Ukraine"],2],
    ["Quel pays a pour capitale Chisinau ?",["Irlande","Maroc","Moldavie","Salomon (Îles)"],2],
    ["Quel pays a pour capitale Monaco ?",["Cameroun","Monaco","Salvador","Portugal"],1],
    ["Quel pays a pour capitale Oulan-Bator ?",["Mongolie","Biélorussie","Roumanie","Papouasie-Nouvelle-Guinée"],0],
    ["Quel pays a pour capitale Podgorica ?",["Liechtenstein","Colombie","Monténégro","Burkina Faso"],2],
    ["Quel pays a pour capitale Maputo ?",["Japon","Mozambique","Lettonie","République tchèque"],1],
    ["Quel pays a pour capitale Windhoek ?",["Pérou","Brésil","Namibie","Marshall (Îles)"],2],
    ["Quel pays a pour capitale Yaren ?",["Suriname","Équateur","Palaos","Nauru"],3],
    ["Quel pays a pour capitale Katmandou ?",["Inde","Népal","Luxembourg","Libye"],1],
    ["Quel pays a pour capitale Managua ?",["Israël","Nauru","Nicaragua","Mexique"],2],
    ["Quel pays a pour capitale Niamey ?",["Palaos","Eswatini","Niger","Congo (Brazzaville)"],2],
    ["Quel pays a pour capitale Abuja ?",["Nigéria","Kazakhstan","Salomon (Îles)","Liberia"],0],
    ["Quel pays a pour capitale Oslo ?",["Cuba","Brunei","Norvège","République centrafricaine"],2],
    ["Quel pays a pour capitale Wellington ?",["Nouvelle-Zélande","Gambie","Salvador","Équateur"],0],
    ["Quel pays a pour capitale Mascate ?",["Oman","Kenya","Gabon","Laos"],0],
    ["Quel pays a pour capitale Kampala ?",["Palaos","Ouganda","Hongrie","Allemagne"],1],
    ["Quel pays a pour capitale Tachkent ?",["Bahamas","Tanzanie","Ouzbékistan","Namibie"],2],
    ["Quel pays a pour capitale Islamabad ?",["Russie","Pakistan","Hongrie","Belize"],1],
    ["Quel pays a pour capitale Ngerulmud ?",["Afghanistan","Kazakhstan","Palaos","Syrie"],2],
    ["Quel pays a pour capitale Panama ?",["Panama","Monaco","Bahamas","Zambie"],0],
    ["Quel pays a pour capitale Port Moresby ?",["Arménie","Ouganda","Maroc","Papouasie-Nouvelle-Guinée"],3],
    ["Quel pays a pour capitale Asuncion ?",["Guinée","Haïti","Liechtenstein","Paraguay"],3],
    ["Quel pays a pour capitale Amsterdam ?",["Maroc","Pays-Bas","Niger","Kazakhstan"],1],
    ["Quel pays a pour capitale Lima ?",["Trinité-et-Tobago","Maldives","Pérou","Eswatini"],2],
    ["Quel pays a pour capitale Manille ?",["Philippines","Bahamas","Liechtenstein","Cap-Vert"],0],
    ["Quel pays a pour capitale Varsovie ?",["Vatican","République centrafricaine","Bangladesh","Pologne"],3],
    ["Quel pays a pour capitale Lisbonne ?",["Philippines","Niger","Italie","Portugal"],3],
    ["Quel pays a pour capitale Doha ?",["Guatemala","Qatar","Maldives","Irlande"],1],
    ["Quel pays a pour capitale Bangui ?",["Guinée","Soudan","Soudan du Sud","République centrafricaine"],3],
    ["Quel pays a pour capitale Saint-Domingue ?",["République dominicaine","Bahreïn","Bénin","Comores"],0],
    ["Quel pays a pour capitale Prague ?",["Lesotho","Indonésie","Égypte","République tchèque"],3],
    ["Quel pays a pour capitale Bucarest ?",["Malaisie","Tadjikistan","Roumanie","Liban"],2],
    ["Quel pays a pour capitale Londres ?",["Espagne","Royaume-Uni","Tunisie","Japon"],1],
    ["Quel pays a pour capitale Moscou ?",["Maroc","Russie","Irlande","Pologne"],1],
    ["Quel pays a pour capitale Kigali ?",["Bosnie-Herzégovine","Guyana","Cambodge","Rwanda"],3],
    ["Quel pays a pour capitale Saint-Marin ?",["Nauru","Paraguay","Saint-Marin","Maroc"],2],
    ["Quel pays a pour capitale Honiara ?",["Birmanie (Myanmar)","Suède","Salomon (Îles)","Brunei"],2],
    ["Quel pays a pour capitale San Salvador ?",["Brunei","Salvador","Paraguay","Iran"],1],
    ["Quel pays a pour capitale Apia ?",["Guatemala","Cambodge","Salvador","Samoa"],3],
    ["Quel pays a pour capitale Sao Tomé ?",["Vatican","Paraguay","Macédoine du Nord","Sao Tomé-et-Principe"],3],
    ["Quel pays a pour capitale Dakar ?",["Timor oriental","Slovaquie","Burundi","Sénégal"],3],
    ["Quel pays a pour capitale Belgrade ?",["Saint-Marin","Azerbaïdjan","Serbie","Indonésie"],2],
    ["Quel pays a pour capitale Victoria ?",["Mexique","Bosnie-Herzégovine","Trinité-et-Tobago","Seychelles"],3],
    ["Quel pays a pour capitale Freetown ?",["Guyana","Niger","Sierra Leone","Paraguay"],2],
    ["Quel pays a pour capitale Singapour ?",["Danemark","Albanie","Singapour","Biélorussie"],2],
    ["Quel pays a pour capitale Bratislava ?",["Irlande","Vanuatu","Slovaquie","Liban"],2],
    ["Quel pays a pour capitale Ljubljana ?",["Slovénie","Jordanie","Serbie","Bahreïn"],0],
    ["Quel pays a pour capitale Mogadiscio ?",["Somalie","Estonie","Suisse","Jordanie"],0],
    ["Quel pays a pour capitale Khartoum ?",["Congo (RDC)","Syrie","Soudan","Birmanie (Myanmar)"],2],
    ["Quel pays a pour capitale Djouba ?",["Bolivie","Guatemala","Papouasie-Nouvelle-Guinée","Soudan du Sud"],3],
    ["Quel pays a pour capitale Sri Jayawardenepura Kotte ?",["Sri Lanka","Italie","Laos","Monténégro"],0],
    ["Quel pays a pour capitale Stockholm ?",["Kiribati","Malaisie","Burkina Faso","Suède"],3],
    ["Quel pays a pour capitale Berne ?",["Salvador","Suisse","Pays-Bas","Bhoutan"],1],
    ["Quel pays a pour capitale Paramaribo ?",["Malawi","Tanzanie","Suriname","Sénégal"],2],
    ["Quel pays a pour capitale Damas ?",["Slovaquie","Syrie","Liban","Ghana"],1],
    ["Quel pays a pour capitale Douchanbé ?",["Estonie","Chili","Iran","Tadjikistan"],3],
    ["Quel pays a pour capitale Dodoma ?",["Somalie","Bosnie-Herzégovine","Royaume-Uni","Tanzanie"],3],
    ["Quel pays a pour capitale N’Djamena ?",["Tchad","Colombie","Suède","Roumanie"],0],
    ["Quel pays a pour capitale Bangkok ?",["Liberia","Zambie","Paraguay","Thaïlande"],3],
    ["Quel pays a pour capitale Dili ?",["Ghana","Timor oriental","Sri Lanka","Iran"],1],
    ["Quel pays a pour capitale Lomé ?",["Brunei","Grèce","Togo","Hongrie"],2],
    ["Quel pays a pour capitale Nuku'alofa ?",["Micronésie","Tonga","Canada","Indonésie"],1],
    ["Quel pays a pour capitale Port-d’Espagne ?",["Iran","Moldavie","Trinité-et-Tobago","Azerbaïdjan"],2],
    ["Quel pays a pour capitale Tunis ?",["Bolivie","Guinée équatoriale","Mexique","Tunisie"],3],
    ["Quel pays a pour capitale Achgabat ?",["Turkménistan","Brunei","Zimbabwe","Panama"],0],
    ["Quel pays a pour capitale Ankara ?",["Indonésie","République tchèque","Turquie","Argentine"],2],
    ["Quel pays a pour capitale Funafuti ?",["Roumanie","Tuvalu","Malawi","Colombie"],1],
    ["Quel pays a pour capitale Kiev ?",["Ukraine","Grèce","Malawi","Slovaquie"],0],
    ["Quel pays a pour capitale Montevideo ?",["Palaos","Uruguay","Lettonie","Albanie"],1],
    ["Quel pays a pour capitale Port-Vila ?",["Chypre","Vanuatu","Slovénie","Inde"],1],
    ["Quel pays a pour capitale Cité du Vatican ?",["Mauritanie","Vatican","Serbie","Sénégal"],1],
    ["Quel pays a pour capitale Caracas ?",["Allemagne","Micronésie","Venezuela","Éthiopie"],2],
    ["Quel pays a pour capitale Hanoï ?",["Soudan du Sud","Indonésie","Vietnam","Panama"],2],
    ["Quel pays a pour capitale Sanaa ?",["Yémen","Belize","Guyana","Sri Lanka"],0],
    ["Quel pays a pour capitale Lusaka ?",["Grèce","Vietnam","Zambie","Eswatini"],2],
    ["Quel pays a pour capitale Harare ?",["Tonga","Zimbabwe","Marshall (Îles)","Serbie"],1]
  ],
  flags: [
    ["Quel drapeau est blanc avec une feuille d’érable rouge au centre et deux bandes rouges verticales ?",["Burkina Faso","Canada","Zimbabwe","Paraguay"],1],
    ["Quel drapeau est blanc avec un simple disque rouge (le soleil) au centre ?",["Sao Tomé-et-Principe","Micronésie","Hongrie","Japon"],3],
    ["Quel drapeau est treize bandes rouges et blanches avec un canton bleu à 50 étoiles blanches ?",["Qatar","États-Unis","Ghana","Irak"],1],
    ["Quel drapeau est l’Union Jack, superposition de croix bleue, blanche et rouge ?",["Costa Rica","Danemark","Monaco","Royaume-Uni"],3],
    ["Quel drapeau est une croix blanche sur fond rouge, en forme de carré ?",["Suisse","Liberia","Guinée équatoriale","Azerbaïdjan"],0],
    ["Quel drapeau est un croissant et une étoile blancs sur fond rouge ?",["Grèce","Turquie","Gambie","Inde"],1],
    ["Quel drapeau est un losange jaune sur fond vert, avec un globe bleu et une devise inscrite ?",["Philippines","Népal","Brésil","Costa Rica"],2],
    ["Quel drapeau est un symbole rouge et bleu en forme de yin-yang entouré de quatre trigrammes noirs sur fond blanc ?",["Corée du Sud","Maroc","Ghana","Bénin"],0],
    ["Quel drapeau est une étoile de David bleue entre deux bandes bleues horizontales sur fond blanc ?",["Israël","Mali","Sao Tomé-et-Principe","Malte"],0],
    ["Quel drapeau est des bandes safran, blanche et verte avec une roue bleue au centre ?",["Luxembourg","Nauru","Inde","Congo (RDC)"],2],
    ["Quel drapeau est une grande étoile jaune entourée de quatre petites étoiles jaunes sur fond rouge ?",["Suriname","Chine","Pakistan","Gambie"],1],
    ["Quel drapeau est une seule grande étoile jaune à cinq branches sur fond rouge ?",["Biélorussie","Vietnam","Rwanda","Japon"],1],
    ["Quel drapeau est un triangle rouge avec une étoile blanche, des bandes bleues et blanches ?",["Brunei","Cuba","Timor oriental","Lettonie"],1],
    ["Quel drapeau est le seul drapeau national non rectangulaire au monde, formé de deux triangles empilés ?",["Canada","Corée du Sud","Salomon (Îles)","Népal"],3],
    ["Quel drapeau est un tricolore vert-blanc-rouge avec un aigle dévorant un serpent au centre ?",["Fidji","Mexique","Andorre","Kirghizistan"],1],
    ["Quel drapeau est vert et blanc avec un croissant et une étoile rouges ?",["Algérie","Corée du Sud","Liberia","Colombie"],0],
    ["Quel drapeau est vert avec un croissant et une étoile blancs, et une bande blanche verticale au mât ?",["Bahreïn","Éthiopie","Pakistan","Nicaragua"],2],
    ["Quel drapeau est un disque rouge décentré sur fond vert ?",["Arménie","Namibie","Afrique du Sud","Bangladesh"],3],
    ["Quel drapeau est un disque doré décentré sur fond bleu ciel ?",["Tchad","Palaos","Sénégal","Philippines"],1],
    ["Quel drapeau est un lion doré tenant une épée sur fond bordeaux, avec des bandes vertes et safran ?",["Sri Lanka","Iran","Nouvelle-Zélande","Royaume-Uni"],0],
    ["Quel drapeau est un dragon blanc sur un fond divisé en diagonale, jaune et orange ?",["Bhoutan","Albanie","Luxembourg","Bangladesh"],0],
    ["Quel drapeau est un tricolore vertical noir, jaune et rouge ?",["Cuba","Belgique","Monténégro","Haïti"],1],
    ["Quel drapeau est des bandes horizontales noire, rouge et or ?",["Allemagne","Égypte","Israël","Guinée"],0],
    ["Quel drapeau est un tricolore vertical vert, blanc et rouge ?",["République centrafricaine","Jordanie","Belize","Italie"],3],
    ["Quel drapeau est un tricolore vertical vert, blanc et orange ?",["Égypte","Autriche","Islande","Irlande"],3],
    ["Quel drapeau est un tricolore vertical orange, blanc et vert ?",["Mexique","Bosnie-Herzégovine","Côte d’Ivoire","Azerbaïdjan"],2],
    ["Quel drapeau est des bandes horizontales orange, blanche et verte avec un disque orange au centre ?",["Samoa","Niger","Autriche","Monaco"],1],
    ["Quel drapeau est des bandes horizontales vert, jaune et bleu ?",["Maurice","États-Unis","Panama","Gabon"],3],
    ["Quel drapeau est une croix diagonale dorée sur un fond divisé en vert et noir ?",["Jamaïque","Kiribati","Canada","Ukraine"],0],
    ["Quel drapeau est une croix bleue bordée de blanc sur fond rouge ?",["Norvège","Autriche","Honduras","Rwanda"],0],
    ["Quel drapeau est une croix jaune sur fond bleu ?",["France","Laos","Croatie","Suède"],3],
    ["Quel drapeau est une croix bleue sur fond blanc ?",["Finlande","Vanuatu","Roumanie","Burkina Faso"],0],
    ["Quel drapeau est une croix blanche sur fond rouge ?",["République tchèque","Guyana","Timor oriental","Danemark"],3],
    ["Quel drapeau est une croix rouge bordée de blanc sur fond bleu ?",["Islande","Lituanie","Suisse","Bahreïn"],0],
    ["Quel drapeau est une croix blanche dans le coin, avec des bandes bleues et blanches horizontales ?",["Sénégal","Pays-Bas","Madagascar","Grèce"],3],
    ["Quel drapeau est une seule étoile blanche à cinq branches sur fond bleu ciel ?",["Qatar","Danemark","Somalie","Tonga"],2],
    ["Quel drapeau est une étoile verte à cinq branches (pentagramme) sur fond rouge ?",["Bangladesh","Jordanie","Maroc","Fidji"],2],
    ["Quel drapeau est une inscription blanche et un sabre blanc sur fond vert ?",["Singapour","Arabie saoudite","Ghana","Russie"],1],
    ["Quel drapeau est une bande blanche au bord dentelé et un fond bordeaux foncé ?",["Tuvalu","Sri Lanka","Qatar","Marshall (Îles)"],2],
    ["Quel drapeau est une bande blanche au bord dentelé et un fond rouge ?",["Argentine","Jordanie","Iran","Bahreïn"],3],
    ["Quel drapeau est un oiseau de paradis et la Croix du Sud sur une diagonale noire et rouge ?",["Estonie","Thaïlande","Papouasie-Nouvelle-Guinée","Maldives"],2],
    ["Quel drapeau est la Croix du Sud rouge bordée de blanc sur fond bleu, avec l’Union Jack en canton ?",["Suisse","Ukraine","Nouvelle-Zélande","Cuba"],2],
    ["Quel drapeau est l’Union Jack en canton, une grande étoile et la Croix du Sud sur fond bleu ?",["Australie","Palaos","Birmanie (Myanmar)","Togo"],0],
    ["Quel drapeau est des bandes bleu ciel et blanche avec un soleil doré au centre ?",["Bulgarie","Canada","Argentine","Guinée"],2],
    ["Quel drapeau est une étoile blanche sur un carré bleu, avec des bandes blanche et rouge ?",["Turkménistan","Tchad","Chili","Pakistan"],2],
    ["Quel drapeau est la silhouette cuivrée de l’île avec deux rameaux d’olivier sur fond blanc ?",["Croatie","Chypre","Seychelles","Islande"],1],
    ["Quel drapeau est un soleil doré et un aigle stylisé sur fond bleu ciel, bordé d’un motif nomade ?",["Brésil","Kazakhstan","Nigéria","Djibouti"],1],
    ["Quel drapeau est un emblème doré (soyombo) sur une bande rouge, entre deux bandes rouges et une bleue ?",["Liban","Mongolie","France","Luxembourg"],1],
    ["Quel drapeau est un disque blanc sur une large bande bleue, bordée de rouge ?",["Slovaquie","Vietnam","Russie","Laos"],3],
    ["Quel drapeau est un cèdre vert sur une bande blanche, entre deux bandes rouges ?",["Mauritanie","Liban","Malaisie","Bulgarie"],1],
    ["Quel drapeau est un écu armorié et une sphère armillaire jaune sur fond vert et rouge ?",["Tanzanie","Islande","Monténégro","Portugal"],3],
    ["Quel drapeau est des bandes rouge, jaune et rouge avec des armoiries à gauche ?",["Suède","Irak","Espagne","Nauru"],2],
    ["Quel drapeau est un tricolore bleu, jaune et rouge avec des armoiries au centre ?",["Jamaïque","Guinée","Monaco","Andorre"],3],
    ["Quel drapeau est un triangle jaune et des étoiles blanches sur fond bleu ?",["Mauritanie","Tchad","Bosnie-Herzégovine","Oman"],2],
    ["Quel drapeau est un soleil rouge avec un motif de yourte (tunduk) sur fond rouge ?",["Timor oriental","Azerbaïdjan","Bolivie","Kirghizistan"],3],
    ["Quel drapeau est une croix rouge sur fond blanc, accompagnée de quatre petites croix rouges ?",["Djibouti","Arménie","Géorgie","Bolivie"],2],
    ["Quel drapeau est une croix de George dans le coin supérieur, sur un fond blanc et rouge ?",["Cap-Vert","Malte","Botswana","Pakistan"],1],
    ["Quel drapeau est des bandes rouges et blanches avec un croissant et une étoile à 14 branches en canton bleu ?",["Macédoine du Nord","Croatie","Malaisie","Uruguay"],2],
    ["Quel drapeau est un croissant et cinq étoiles blanches sur une bande rouge, au-dessus d’une bande blanche ?",["Pays-Bas","Singapour","Angola","Jordanie"],1],
    ["Quel drapeau est un triangle blanc avec un soleil et trois étoiles, entre des bandes bleue et rouge ?",["Yémen","Philippines","Suisse","Cameroun"],1],
    ["Quel drapeau est un boomerang jaune en forme de Y sur fond noir, rouge et vert ?",["États-Unis","Cap-Vert","Vanuatu","Micronésie"],2],
    ["Quel drapeau est l’Union Jack en canton et des armoiries sur fond bleu ciel ?",["Eswatini","Canada","Jordanie","Fidji"],3],
    ["Quel drapeau est un bouclier zoulou noir et blanc avec des lances sur fond bleu, jaune et rouge ?",["Corée du Sud","Eswatini","Ouzbékistan","Mongolie"],1],
    ["Quel drapeau est un bouclier et des lances maasaï sur des bandes noire, rouge et verte ?",["Royaume-Uni","Bahamas","Kenya","Saint-Marin"],2],
    ["Quel drapeau est un Y horizontal multicolore, unique parmi les drapeaux nationaux ?",["Afrique du Sud","Allemagne","Saint-Marin","Laos"],0],
    ["Quel drapeau est un oiseau de pierre doré sur un triangle blanc, entouré de bandes multicolores ?",["Zimbabwe","Tuvalu","Ouzbékistan","Papouasie-Nouvelle-Guinée"],0],
    ["Quel drapeau est une bande diagonale noire bordée de jaune, entre des triangles vert et bleu ?",["Tanzanie","Seychelles","Mali","Libye"],0],
    ["Quel drapeau est un soleil doré sur des bandes bleue, jaune et verte ?",["Rwanda","Mozambique","Bosnie-Herzégovine","Pologne"],0],
    ["Quel drapeau est une étoile noire sur des bandes rouge, jaune et verte ?",["Somalie","Ghana","Belize","Tchad"],1],
    ["Quel drapeau est un pentagramme jaune sur un disque bleu, sur des bandes vert, jaune et rouge ?",["Éthiopie","Grèce","Angola","Suisse"],0],
    ["Quel drapeau est un aigle doré sur des bandes rouge, blanche et noire ?",["Égypte","Grèce","Eswatini","Libye"],0],
    ["Quel drapeau est une inscription verte sur une bande blanche, entre des bandes rouge et noire ?",["Trinité-et-Tobago","Irak","Zimbabwe","Côte d’Ivoire"],1],
    ["Quel drapeau est un emblème rouge central sur des bandes vert, blanc et rouge ?",["Arménie","Togo","Iran","Israël"],2],
    ["Quel drapeau est une bande rouge verticale au mât, devant des bandes vert, blanc et noir ?",["Émirats arabes unis","Yémen","Allemagne","Pérou"],0],
    ["Quel drapeau est une étoile rouge dans un cercle blanc, sur une large bande rouge bordée de blanc et de bleu ?",["Corée du Nord","Belgique","Nigéria","Timor oriental"],0],
    ["Quel drapeau est quatre quadrants blanc et bleu avec une étoile bleue et une étoile rouge ?",["États-Unis","Belgique","Panama","Corée du Sud"],2],
    ["Quel drapeau est des bandes bleu ciel et blanche avec des armoiries au centre ?",["Guyana","Égypte","Guatemala","Croatie"],2],
    ["Quel drapeau est une bande diagonale noire bordée de blanc sur fond rouge ?",["Somalie","Bolivie","Trinité-et-Tobago","Albanie"],2],
    ["Quel drapeau est des bandes horizontales rouge, jaune et verte avec des armoiries au centre ?",["Bolivie","Monténégro","Brunei","Thaïlande"],0],
    ["Quel drapeau est une large bande jaune au-dessus de bandes bleue et rouge ?",["Suède","Sao Tomé-et-Principe","Colombie","Oman"],2],
    ["Quel drapeau est des bandes jaune, bleue et rouge avec un arc de huit étoiles blanches ?",["Venezuela","Royaume-Uni","Tuvalu","Salvador"],0],
    ["Quel drapeau est des bandes jaune, bleue et rouge avec de grandes armoiries au centre ?",["Malaisie","Zimbabwe","Équateur","Hongrie"],2],
    ["Quel drapeau est une bande blanche centrale avec des armoiries, entre deux bandes rouges ?",["Pérou","Panama","Indonésie","Malaisie"],0],
    ["Quel drapeau est une grue couronnée sur un cercle blanc, sur des bandes noire, jaune et rouge répétées ?",["Brunei","République dominicaine","Mozambique","Ouganda"],3],
    ["Quel drapeau est un aigle orange au-dessus d’une bande verte, avec des bandes rouge, noire et orange au bord ?",["Chine","Bénin","Sénégal","Zambie"],3],
    ["Quel drapeau est une diagonale bicolore bleu-vert bordée de blanc, avec un soleil doré ?",["Comores","Nigéria","Corée du Sud","Namibie"],3],
    ["Quel drapeau est une large bande bleu ciel traversée d’une bande noire bordée de blanc ?",["Chypre","Côte d’Ivoire","Botswana","Birmanie (Myanmar)"],2]
  ],
  literature: [
    ["Qui a écrit « Les Misérables » ?",["Émile Zola","Victor Hugo","Gustave Flaubert","Alexandre Dumas"],1],
    ["Qui a écrit « Le Petit Prince » ?",["Antoine de Saint-Exupéry","Jules Verne","Marcel Pagnol","Albert Camus"],0],
    ["Qui est l'auteure de la saga « Harry Potter » ?",["J.K. Rowling","Suzanne Collins","Stephenie Meyer","Veronica Roth"],0],
    ["Quel auteur russe a écrit « Guerre et Paix » ?",["Fiodor Dostoïevski","Léon Tolstoï","Anton Tchekhov","Ivan Tourgueniev"],1],
    ["Qui a écrit le roman « 1984 » ?",["Aldous Huxley","Ray Bradbury","George Orwell","H.G. Wells"],2],
    ["Quel auteur français a écrit « Madame Bovary » ?",["Gustave Flaubert","Guy de Maupassant","Stendhal","Honoré de Balzac"],0],
    ["Qui a écrit « Don Quichotte » ?",["Miguel de Cervantès","Fernando Pessoa","Gabriel García Márquez","Jorge Luis Borges"],0],
    ["Quel poète français a écrit le recueil « Les Fleurs du mal » ?",["Arthur Rimbaud","Paul Verlaine","Charles Baudelaire","Victor Hugo"],2],
    ["Qui a écrit « Vingt mille lieues sous les mers » ?",["H.G. Wells","Jules Verne","Herman Melville","Daniel Defoe"],1],
    ["Quel auteur est connu pour « À la recherche du temps perdu » ?",["Marcel Proust","André Gide","Louis Aragon","Romain Rolland"],0],
    ["Qui a écrit la trilogie « Le Seigneur des Anneaux » ?",["C.S. Lewis","J.R.R. Tolkien","George R.R. Martin","Terry Pratchett"],1],
    ["Quel écrivain français a créé le personnage cambrioleur Arsène Lupin ?",["Gaston Leroux","Maurice Leblanc","Georges Simenon","Pierre Boileau"],1],
    ["Qui a écrit « Crime et Châtiment » ?",["Léon Tolstoï","Nicolas Gogol","Fiodor Dostoïevski","Ivan Tourgueniev"],2],
    ["Quel auteur britannique a créé le personnage de Sherlock Holmes ?",["Agatha Christie","Arthur Conan Doyle","Wilkie Collins","G.K. Chesterton"],1],
    ["Qui a écrit « L'Étranger » ?",["Jean-Paul Sartre","Albert Camus","André Malraux","Simone de Beauvoir"],1],
    ["Quel auteur français a écrit « Germinal » ?",["Émile Zola","Gustave Flaubert","Guy de Maupassant","Honoré de Balzac"],0],
    ["Qui a écrit « Les Trois Mousquetaires » ?",["Victor Hugo","Alexandre Dumas","Prosper Mérimée","Théophile Gautier"],1],
    ["Quel auteur britannique a écrit « Sa Majesté des Mouches » ?",["George Orwell","William Golding","Graham Greene","Ian McEwan"],1],
    ["Qui a écrit « Orgueil et Préjugés » ?",["Charlotte Brontë","Jane Austen","Emily Brontë","Virginia Woolf"],1],
    ["Quel poète grec de l'Antiquité est l'auteur de « L'Odyssée » ?",["Sophocle","Hésiode","Homère","Euripide"],2],
    ["Qui a écrit « Cent ans de solitude » ?",["Mario Vargas Llosa","Jorge Luis Borges","Gabriel García Márquez","Pablo Neruda"],2],
    ["Quel auteur français des Lumières a écrit « Candide » ?",["Voltaire","Diderot","Montesquieu","Rousseau"],0],
    ["Qui a écrit « Le Rouge et le Noir » ?",["Balzac","Stendhal","Flaubert","Maupassant"],1],
    ["Quel auteur américain a créé le personnage de Tarzan ?",["Mark Twain","Jack London","Edgar Rice Burroughs","Herman Melville"],2],
    ["Qui a écrit « Notre-Dame de Paris » ?",["Victor Hugo","Alexandre Dumas","Prosper Mérimée","Théophile Gautier"],0],
    ["Quel terme désigne un récit dans lequel un auteur raconte sa propre vie ?",["Une biographie","Une autobiographie","Un essai","Un roman historique"],1],
    ["Qui a écrit la saga « Le Trône de fer » (« A Song of Ice and Fire ») ?",["Patrick Rothfuss","George R.R. Martin","Brandon Sanderson","Robin Hobb"],1],
    ["Qui a écrit « Frankenstein » ?",["Bram Stoker","Mary Shelley","Emily Brontë","Ann Radcliffe"],1],
    ["Quel auteur français a écrit « Le Mystère de la chambre jaune » ?",["Gaston Leroux","Maurice Leblanc","Georges Simenon","Jules Verne"],0],
    ["Qui a écrit « Voyage au bout de la nuit » ?",["Louis-Ferdinand Céline","Jean Giono","André Gide","Marcel Aymé"],0],
    ["Quel type de poème comporte traditionnellement quatorze vers ?",["Une ode","Un sonnet","Une ballade","Un haïku"],1],
    ["Qui a écrit « Bel-Ami » ?",["Guy de Maupassant","Gustave Flaubert","Émile Zola","Honoré de Balzac"],0],
    ["Quel auteur britannique a créé le monde imaginaire de Narnia ?",["J.R.R. Tolkien","C.S. Lewis","Philip Pullman","Lewis Carroll"],1],
    ["Qui a écrit « Le Vieil Homme et la Mer » ?",["F. Scott Fitzgerald","Ernest Hemingway","John Steinbeck","William Faulkner"],1],
    ["Quel auteur français du XVIIe siècle est célèbre pour ses fables mettant en scène des animaux ?",["Charles Perrault","Jean de La Fontaine","Nicolas Boileau","Blaise Pascal"],1],
    ["Qui a écrit « Dracula » ?",["Mary Shelley","Bram Stoker","H.P. Lovecraft","Edgar Allan Poe"],1],
    ["Qui a écrit « Da Vinci Code » ?",["John Grisham","Dan Brown","Michael Crichton","Tom Clancy"],1],
    ["Quel prestigieux prix littéraire français est décerné chaque année en automne ?",["Le prix Renaudot","Le prix Goncourt","Le prix Femina","Le prix Médicis"],1]
  ],
  dance: [
    ["Quelle danse de couple, mélancolique et sensuelle, est originaire d'Argentine ?",["La salsa","Le tango","La valse","Le flamenco"],1],
    ["Quelle danse espagnole s'accompagne traditionnellement de castagnettes et de guitare ?",["Le flamenco","La sardane","Le paso doble","La sévillane"],0],
    ["Quelle danse de couple, très populaire, est associée à Cuba et à la musique latine ?",["La bachata","La salsa","La rumba","Le merengue"],1],
    ["En combien de temps se danse traditionnellement la valse viennoise ?",["2 temps","3 temps","4 temps","6 temps"],1],
    ["Quel style de danse classique se pratique traditionnellement sur des chaussons appelés pointes ?",["Le ballet classique","La danse contemporaine","Le jazz","Le modern'jazz"],0],
    ["Dans quel quartier de New York le hip-hop est-il né dans les années 1970 ?",["Manhattan","Le Bronx","Brooklyn","Queens"],1],
    ["Quelle danse brésilienne rythmée est emblématique du carnaval de Rio ?",["La samba","La bossa nova","Le forró","Le maxixe"],0],
    ["Quel art brésilien mêle danse, acrobaties et art martial, souvent pratiqué en cercle avec des instruments ?",["La capoeira","Le frevo","Le maculelê","Le jongo"],0],
    ["Quelle danse de cabaret française du XIXe siècle est associée au Moulin Rouge ?",["Le french cancan","La bourrée","La gavotte","La farandole"],0],
    ["Quel style de danse classique indien raconte des histoires à travers des gestes précis des mains, appelés mudras ?",["Le Kathak","Le Bharatanatyam","Le Kuchipudi","Le Odissi"],1],
    ["Quel style de danse, très populaire dans les discothèques des années 1970, est associé à la musique disco ?",["Le disco","Le funk","Le boogie","Le swing"],0],
    ["Quel pas de danse, donnant l'illusion de glisser en arrière, a été popularisé par Michael Jackson ?",["Le moonwalk","Le robot","Le breakdance","Le popping"],0],
    ["Quelle danse de salon, inspirée de la corrida espagnole, met en scène le torero et sa cape ?",["Le paso doble","Le tango","La rumba","Le quickstep"],0],
    ["Quel style de danse, né aux États-Unis dans les années 1950, est associé à la musique rock and roll ?",["Le lindy hop","Le rock'n'roll","Le charleston","Le be-bop"],1],
    ["Comment appelle-t-on la danse orientale traditionnelle originaire du Moyen-Orient, centrée sur des mouvements du bassin ?",["La danse du ventre","Le dabké","La danse berbère","Le sirtaki"],0],
    ["Quelle danse en ligne, popularisée par une chanson espagnole des années 1990, a connu un succès mondial ?",["La Macarena","La Lambada","Le Madison","Le Cha-cha-cha"],0],
    ["Comment appelle-t-on le jeu-danse d'origine caribéenne où l'on passe sous une barre en se penchant en arrière ?",["Le limbo","Le zouk","Le compas","Le dancehall"],0],
    ["Quelle danse de bal traditionnelle française, dansée à quatre couples, était très populaire au XIXe siècle ?",["La polka","Le quadrille","La mazurka","La bourrée"],1],
    ["Quelle danse populaire des années 1920, née à Charleston en Caroline du Sud, donne son nom à cette décennie festive ?",["Le charleston","Le black bottom","Le shimmy","Le foxtrot"],0],
    ["Quelle danse de couple, originaire de République dominicaine, se danse rapidement en petits pas serrés ?",["Le merengue","La samba","Le paso doble","La rumba"],0],
    ["Quel style de danse classique du nord de l'Inde combine mouvements rapides des pieds et rotations ?",["Le Bharatanatyam","Le Kathak","L'Odissi","Le Manipuri"],1],
    ["Quel style de danse à claquettes se pratique avec des chaussures munies de plaques métalliques ?",["Le tap dance (claquettes)","Le flamenco","Le clog dancing","La gigue"],0],
    ["Quelle danse née dans la scène ballroom afro-américaine et latino de New York dans les années 1980 met en avant des poses inspirées de la mode ?",["Le voguing","Le krump","Le popping","Le locking"],0],
    ["Quelle danse de swing, née à Harlem dans les années 1920-1930, est dansée sur du jazz rapide ?",["Le lindy hop","Le charleston","Le be-bop","Le shag"],0],
    ["Quel style de danse du XXe siècle s'affranchit des codes stricts et des figures imposées du ballet classique ?",["La danse contemporaine","Le ballet romantique","La danse académique","Le mime"],0],
    ["Le popping et le locking sont des styles appartenant à quelle famille de danse plus large ?",["La danse urbaine (hip-hop)","La danse classique","La danse de salon","La danse folklorique"],0],
    ["Quelle danse traditionnelle française, souvent dansée en ronde ou en chaîne lors des fêtes populaires, porte le nom d'une danse provençale ?",["La farandole","Le quadrille","La bourrée","La gavotte"],0],
    ["Quel élément vestimentaire caractérise typiquement la danseuse de flamenco sur scène ?",["Un tutu","Une robe à volants","Un kimono","Une jupe plissée écossaise"],1],
    ["Quelle danse traditionnelle hawaïenne raconte une histoire à travers des mouvements des mains et des hanches ?",["Le hula","Le haka","Le tamouré","Le siva"],0],
    ["Quelle danse traditionnelle grecque se danse en cercle, les danseurs se tenant par les épaules ?",["Le sirtaki","Le kalamatianos","Le tsamiko","Le zeibekiko"],0],
    ["Comment appelle-t-on le saut classique de ballet où le danseur croise et décroise rapidement les jambes en l'air ?",["Le grand jeté","L'entrechat","Le fouetté","L'arabesque"],1],
    ["Quelle danse de couple polonaise à trois temps a inspiré plusieurs compositions célèbres de Chopin ?",["La mazurka","La polonaise","La polka","La czardas"],0],
    ["Quelle danse folklorique irlandaise se caractérise par des mouvements de jambes très rapides et un buste presque immobile ?",["La danse irlandaise (step dance)","La gigue écossaise","Le clog dancing","Le morris dance"],0],
    ["Comment appelle-t-on le saut suspendu et spectaculaire, symbole du ballet classique, où le danseur semble s'envoler ?",["Le grand jeté","La pirouette","L'arabesque","Le plié"],0],
    ["Quel style de danse de club, énergique et syncopé, est associé à la culture house et techno depuis les années 1980-1990 ?",["Le shuffle dance","Le tango","La valse musette","La bourrée"],0],
    ["Quelle danse de couple née en Angola et popularisée au Portugal et au Brésil se danse sur un rythme lent et sensuel ?",["La kizomba","La bourrée","Le madison","La czardas"],0],
    ["Quel style de danse acrobatique et rythmé inclut des figures comme les « freezes » et les figures au sol ?",["Le breakdance","Le ballet","La valse","Le flamenco"],0],
    ["Quelle danse de bal, rapide et légère, tient son nom d'un pas glissé caractéristique et se danse souvent après le tango en compétition ?",["Le quickstep","Le paso doble","Le cha-cha-cha","Le jive"],0]
  ],
  theatre: [
    ["Qui a écrit « Roméo et Juliette » ?",["Christopher Marlowe","William Shakespeare","Oscar Wilde","George Bernard Shaw"],1],
    ["Qui a écrit « Le Malade imaginaire » ?",["Molière","Racine","Corneille","Marivaux"],0],
    ["Quel dramaturge français est l'auteur de « Cyrano de Bergerac » ?",["Victor Hugo","Edmond Rostand","Alfred de Musset","Eugène Labiche"],1],
    ["Qui a écrit « Hamlet » ?",["William Shakespeare","Christopher Marlowe","Ben Jonson","John Webster"],0],
    ["Quel dramaturge grec de l'Antiquité a écrit « Œdipe roi » ?",["Eschyle","Euripide","Sophocle","Aristophane"],2],
    ["Quel dramaturge norvégien est surnommé le « père du théâtre moderne » avec « Une maison de poupée » ?",["August Strindberg","Henrik Ibsen","Anton Tchekhov","Bertolt Brecht"],1],
    ["Qui a écrit « En attendant Godot » ?",["Eugène Ionesco","Samuel Beckett","Jean Genet","Jean Anouilh"],1],
    ["Quel dramaturge français a écrit « Le Cid » ?",["Jean Racine","Pierre Corneille","Molière","Voltaire"],1],
    ["Qui a écrit « Phèdre » ?",["Jean Racine","Pierre Corneille","Molière","Marivaux"],0],
    ["Quel terme désigne un monologue intérieur qu'un personnage prononce seul sur scène ?",["Un soliloque","Un aparté comique","Un chœur","Un prologue"],0],
    ["Quel terme théâtral désigne l'endroit où les acteurs se préparent avant d'entrer en scène ?",["Le foyer","Les coulisses","La fosse","Le parterre"],1],
    ["Quel terme désigne une pièce de théâtre destinée à faire rire le public ?",["Une tragédie","Une comédie","Un drame","Une élégie"],1],
    ["Quel terme désigne une pièce mettant en scène des personnages illustres frappés par un destin funeste ?",["Une comédie","Une farce","Une tragédie","Un vaudeville"],2],
    ["Quel dramaturge est associé au « théâtre de l'absurde » avec « La Cantatrice chauve » ?",["Samuel Beckett","Eugène Ionesco","Jean Genet","Arthur Adamov"],1],
    ["Quel dramaturge romain de l'Antiquité a écrit des comédies comme « L'Aululaire » ?",["Sénèque","Plaute","Térence","Cicéron"],1],
    ["Comment appelle-t-on une courte scène jouée entre les actes d'une pièce plus longue ?",["Un prologue","Un épilogue","Un intermède","Un tableau"],2],
    ["Quel dramaturge espagnol du Siècle d'or a écrit « La vie est un songe » ?",["Lope de Vega","Pedro Calderón de la Barca","Tirso de Molina","Miguel de Cervantès"],1],
    ["Quel terme désigne un spectacle où les dialogues sont entièrement chantés avec un orchestre ?",["Une opérette","Un opéra","Un ballet","Une comédie musicale"],1],
    ["Quel dramaturge français du XXe siècle a écrit « La Guerre de Troie n'aura pas lieu » ?",["Jean Anouilh","Jean Giraudoux","Jean Cocteau","Marcel Pagnol"],1],
    ["Quel terme théâtral désigne l'espace où se trouvent les musiciens, devant la scène, notamment à l'opéra ?",["La fosse d'orchestre","Le foyer","Le parterre","La corbeille"],0],
    ["Quel dramaturge américain a écrit « Un tramway nommé Désir » ?",["Arthur Miller","Tennessee Williams","Eugene O'Neill","David Mamet"],1],
    ["Quel terme désigne un acteur qui remplace un autre en cas d'absence ?",["Une doublure","Un figurant","Un souffleur","Un régisseur"],0],
    ["Quel genre théâtral italien traditionnel met en scène des personnages masqués improvisant, comme Arlequin ou Pantalon ?",["L'opéra bouffe","La Commedia dell'arte","Le théâtre de marionnettes","Le mélodrame"],1],
    ["Quel personnage masqué et facétieux est emblématique de la Commedia dell'arte ?",["Arlequin","Pierrot","Guignol","Polichinelle"],0],
    ["Quel terme désigne l'auteur qui écrit les dialogues et l'intrigue d'une pièce de théâtre ?",["Le scénariste","Le dramaturge","Le librettiste","Le narrateur"],1],
    ["Quel terme désigne la personne qui dirige les acteurs et organise la mise en scène d'une pièce ?",["Le producteur","Le metteur en scène","Le régisseur général","Le dramaturge"],1],
    ["Quel dramaturge et philosophe français du XXe siècle a écrit « Huis clos » (« L'enfer, c'est les autres ») ?",["Albert Camus","Jean-Paul Sartre","André Malraux","Simone de Beauvoir"],1],
    ["Comment appelle-t-on les applaudissements répétés à la fin d'un spectacle pour faire revenir les acteurs sur scène ?",["Une ovation","Un rappel","Un bis","Un tonnerre"],1],
    ["Quel terme théâtral désigne une grande toile peinte représentant un décor, suspendue en fond de scène ?",["Une toile de fond","Un rideau de scène","Un praticable","Un cyclorama technique"],0],
    ["Quel prix théâtral français prestigieux récompense chaque année les meilleurs spectacles et artistes de la profession ?",["Les Césars","Les Molières","Les Victoires","Les Lauriers"],1],
    ["Quel dramaturge français du XVIIIe siècle a écrit « Le Mariage de Figaro » ?",["Marivaux","Beaumarchais","Diderot","Voltaire"],1],
    ["Quel dramaturge irlandais est l'auteur de « Pygmalion », qui inspira la comédie musicale « My Fair Lady » ?",["Oscar Wilde","George Bernard Shaw","Samuel Beckett","Brian Friel"],1],
    ["Quel dramaturge français du XVIIIe siècle a écrit « Le Jeu de l'amour et du hasard » ?",["Marivaux","Beaumarchais","Molière","Racine"],0],
    ["Quel dramaturge allemand a théorisé la « distanciation » (Verfremdungseffekt) au théâtre ?",["Bertolt Brecht","Friedrich Schiller","Johann Wolfgang von Goethe","Georg Büchner"],0],
    ["Quel terme désigne un personnage secondaire présent sur scène sans texte à dire, pour figurer une foule ?",["Une doublure","Un figurant","Un souffleur","Un cabotin"],1],
    ["Quel terme désigne la personne chargée de souffler discrètement leur texte aux acteurs en cas de trou de mémoire ?",["Le régisseur","Le souffleur","Le machiniste","L'accessoiriste"],1],
    ["Quel dramaturge français du XIXe siècle est célèbre pour ses comédies-vaudevilles comme « Un chapeau de paille d'Italie » ?",["Eugène Labiche","Georges Feydeau","Alfred de Musset","Victor Hugo"],0],
    ["Quel dramaturge français a écrit « On ne badine pas avec l'amour » ?",["Alfred de Musset","Victor Hugo","Alexandre Dumas","Eugène Scribe"],0]
  ],
  judo: [
    ["Quel pays est le berceau du judo ?",["La Corée","La Chine","Le Japon","La Thaïlande"],2],
    ["Qui est le fondateur du judo moderne, à la fin du XIXe siècle ?",["Jigoro Kano","Morihei Ueshiba","Gichin Funakoshi","Mas Oyama"],0],
    ["Quelle couleur de ceinture porte traditionnellement un débutant en judo ?",["Blanche","Jaune","Noire","Marron"],0],
    ["Quelle couleur de ceinture symbolise généralement le plus haut niveau de maîtrise en judo ?",["Blanche","Verte","Noire","Orange"],2],
    ["Comment appelle-t-on la tenue portée par les judokas à l'entraînement et en compétition ?",["Le judogi","Le hakama","Le keikogi de kendo","Le dogi de karaté (autre nom générique)"],0],
    ["Comment appelle-t-on l'immobilisation au sol d'un adversaire en judo ?",["L'osaekomi","Le nage-waza","Le randori","L'uchikomi"],0],
    ["Que signifie littéralement le mot japonais « judo » ?",["La voie de la force","La voie de la souplesse","La voie du guerrier","La voie du sabre"],1],
    ["Dans quel pays le jiu-jitsu brésilien (BJJ) s'est-il particulièrement développé au XXe siècle ?",["Le Japon","Le Brésil","Les États-Unis","Le Portugal"],1],
    ["Quelle famille est historiquement associée au développement et à la popularisation du jiu-jitsu brésilien ?",["La famille Gracie","La famille Kano","La famille Ueshiba","La famille Yamamoto"],0],
    ["Comment appelle-t-on le salut effectué avant et après un combat de judo, en signe de respect ?",["Le rei","Le kiai","Le zanshin","Le mokuso"],0],
    ["Quel revêtement recouvre le sol d'un dojo de judo pour amortir les chutes ?",["Le tatami","Le parquet","Le linoléum","Le gazon synthétique"],0],
    ["Comment appelle-t-on le lieu où l'on pratique le judo et d'autres arts martiaux japonais ?",["Le dojo","Le ring","L'octogone","Le stade"],0],
    ["Comment appelle-t-on une clé de bras visant l'articulation du coude, pratiquée en judo comme en jiu-jitsu ?",["Une clé de bras (juji-gatame)","Un étranglement","Une projection","Une immobilisation"],0],
    ["Comment nomme-t-on, en judo, l'ensemble des techniques d'étranglement ?",["Le shime-waza","L'atemi-waza","Le kansetsu-waza uniquement","Le sutemi-waza"],0],
    ["En quelle année le judo est-il devenu discipline olympique, lors des Jeux de Tokyo ?",["1956","1960","1964","1972"],2],
    ["Quelle nation domine traditionnellement le judo mondial en nombre de médailles olympiques ?",["La France","Le Japon","La Corée du Sud","La Russie"],1],
    ["Comment appelle-t-on les techniques de judo pratiquées au sol, comme les immobilisations et les clés ?",["Le ne-waza","Le tachi-waza","Le kata","Le randori uniquement"],0],
    ["Comment appelle-t-on les techniques de projection debout en judo ?",["Le ne-waza","Le tachi-waza","L'atemi-waza","Le shime-waza"],1],
    ["Quel art martial japonais ancien a directement inspiré Jigoro Kano pour créer le judo ?",["Le kendo","Le ju-jitsu traditionnel (jujutsu)","L'aïkido","Le karaté"],1],
    ["Quel terme désigne l'entraînement libre où deux judokas s'affrontent en appliquant librement leurs techniques ?",["Le randori","L'uchikomi","Le kata","Le shiai"],0],
    ["Quel terme désigne une compétition officielle de judo, par opposition à l'entraînement ?",["Le randori","Le shiai","L'uchikomi","Le kata"],1],
    ["Quel terme désigne l'entraînement répétitif d'une technique sans opposition réelle, pour en automatiser le geste ?",["L'uchikomi","Le randori","Le shiai","Le kumite"],0],
    ["Quel terme japonais désigne un enchaînement codifié de techniques exécuté à deux, sans opposition réelle ?",["Le kata","Le randori","Le shiai","L'uchikomi"],0],
    ["Quel principe fondamental, formulé par Jigoro Kano, résume la philosophie du judo (« la meilleure utilisation de... ») ?",["La force maximale","L'énergie minimale et l'efficacité maximale","La vitesse pure","La résistance totale"],1],
    ["Quel autre grand principe du judo encourage l'entraide et le bénéfice mutuel entre pratiquants ?",["L'entraide et la prospérité mutuelle","La compétition permanente","La domination individuelle","Le secret des techniques"],0],
    ["Quel organe international régit les règles du judo au niveau mondial ?",["La FIFA","La Fédération internationale de judo (IJF)","Le CIO uniquement","La World Karate Federation"],1],
    ["Quel terme désigne, en jiu-jitsu brésilien, l'abandon signalé par un pratiquant soumis à une clé ou un étranglement ?",["La soumission (tap out)","Le waza-ari","L'ippon","Le golden score"],0],
    ["Quelle discipline de combat, dérivée du judo et du jiu-jitsu traditionnel, met l'accent sur le combat au sol et les soumissions ?",["Le sumo","Le jiu-jitsu brésilien","Le kendo","Le karaté"],1],
    ["Quelle technique de judo consiste à faire chuter un adversaire en se sacrifiant soi-même au sol ?",["Le sutemi-waza","L'atemi-waza","Le kansetsu-waza","Le shime-waza"],0],
    ["Quel terme désigne, en judo, les techniques de frappe (non autorisées en compétition mais présentes dans les katas) ?",["L'atemi-waza","Le ne-waza","Le tachi-waza","Le randori"],0],
    ["Quel équipement, souvent une ceinture large en tissu, sert à fermer le judogi à la taille et indique le grade ?",["La obi (ceinture)","Le hakama","Le keikogi","Le zori"],0],
    ["Quel terme désigne le grade obtenu par un judoka au-delà de la ceinture noire, numéroté en degrés (1er, 2e, 3e...) ?",["Le kyu","Le dan","Le mon","Le sho"],1],
    ["Quel terme désigne les grades inférieurs à la ceinture noire, généralement représentés par des ceintures colorées ?",["Le dan","Le kyu","Le sensei","Le sempai"],1],
    ["Comment appelle-t-on le professeur ou l'instructeur de judo dans un dojo ?",["Le sensei","Le sempai","Le kohai","Le shihan uniquement"],0],
    ["Quel judoka néerlandais devint en 1961 le premier champion du monde non japonais de l'histoire ?",["Anton Geesink","Wim Ruska","Willem van der Berg","Peter Seisenbacher"],0]
  ]
};

// V4 : sélection multi-thèmes + exclusion des questions déjà posées dans la partie
// (une question posée dans une manche ne peut plus tomber dans la manche suivante).
function buildQuestionSet(topics, count, multipliers = false, exclude = []) {
  const excludeSet = new Set(exclude || []);
  const list = [...new Set((Array.isArray(topics) ? topics : [topics]).filter(t => QUESTION_BANK[t]))];
  if (!list.length) list.push('general');

  const pools = {}; list.forEach(t => pools[t] = [...QUESTION_BANK[t]].filter(q => !excludeSet.has(q[0])).sort(() => Math.random() - .5));
  const n = list.length, base = Math.floor(count / n), rem = count - base * n;
  const target = {}; list.forEach((t, i) => target[t] = base + (i < rem ? 1 : 0));

  let combined = [];
  list.forEach(t => { const take = Math.min(target[t], pools[t].length); combined = combined.concat(pools[t].splice(0, take)); });
  const shortfall = count - combined.length;
  if (shortfall > 0) {
    const leftover = list.flatMap(t => pools[t]).sort(() => Math.random() - .5);
    combined = combined.concat(leftover.slice(0, shortfall));
  }
  combined = combined.sort(() => Math.random() - .5).slice(0, count);

  const selected = combined.map((q, i) => ({id:`${Date.now()}-${i}-${Math.random().toString(36).slice(2,6)}`, text:q[0], choices:q[1], correct:q[2], multiplier:1}));
  if (multipliers && selected.length >= 4) {
    const positions = [...selected.keys()].sort(() => Math.random() - .5);
    positions.slice(0,3).forEach(i => selected[i].multiplier = 2);
    selected[positions[3]].multiplier = 3;
  }
  return selected;
}
